# Generated by wallpaper_effects.sh
export ANTO426_BACKGROUND="#281f33"
export ANTO426_SURFACE="#635575"
export ANTO426_FOREGROUND="#f6f7fb"
export ANTO426_MUTED="#b9c4d2"
export ANTO426_SELECT="#7f6f93"
export ANTO426_ACCENT="#9579b6"
export ANTO426_BORDER="#817590"
export ANTO426_WALLPAPER="/home/anto426/Pictures/Wallpapers/anime-girl-watching-sunset-city-skyline.jpg"
