#include "internal.h"

const Shortcut anto_shortcuts_shortcuts[] = {
    {"APPLICAZIONI", "SUPER Spazio", "Terminale"},
    {NULL, "SUPER E", "File manager"}, {NULL, "SUPER B", "Browser"},
    {NULL, "ALT Spazio", "Launcher applicazioni"}, {NULL, "SUPER V", "Appunti"},
    {NULL, "SUPER .", "Emoji"}, {NULL, "SUPER N", "Note rapide"},
    {"FINESTRE", "SUPER Q", "Chiudi finestra"},
    {NULL, "SUPER Frecce", "Sposta il focus"},
    {NULL, "SUPER SHIFT Frecce", "Sposta finestra"},
    {NULL, "SUPER CTRL Frecce", "Ridimensiona finestra"},
    {NULL, "SUPER F", "Floating on/off"}, {NULL, "SUPER S", "Fullscreen"},
    {"WORKSPACE", "SUPER 1…9", "Vai allo slot 1…9 del monitor attivo"},
    {NULL, "SUPER 0", "Vai allo slot 10 del monitor attivo"},
    {NULL, "SUPER SHIFT 1…9", "Sposta la finestra nello slot 1…9"},
    {NULL, "SUPER SHIFT 0", "Sposta la finestra nello slot 10"},
    {NULL, "SUPER Tab", "Workspace successivo sul monitor attivo"},
    {"CATTURA", "Print", "Screenshot area"},
    {NULL, "SHIFT Print", "Screenshot finestra"},
    {NULL, "CTRL Print", "Screenshot monitor"},
    {NULL, "F9", "Menu registrazione"},
    {"DESKTOP", "SUPER W", "Galleria wallpaper"},
    {NULL, "SUPER SHIFT W", "Wallpaper casuale"},
    {NULL, "SUPER G", "Mostra/nascondi widget"},
    {NULL, "SUPER CTRL G", "Gestione widget"},
    {"SISTEMA", "SUPER L", "Blocca schermo"},
    {NULL, "SUPER SHIFT P", "Modalità schermi"},
    {NULL, "Tasto Power", "Menu alimentazione"},
};
