#!/usr/bin/env bash

write_zen_theme() {
    local zen_dir="$HOME/.config/zen"
    [[ -d "$zen_dir" ]] || return 0

    ensure_gtk_palette_roles

    local temp_chrome="$tmp_dir/zen_userChrome.css"
    local temp_content="$tmp_dir/zen_userContent.css"

    cat >"$temp_chrome" <<EOF
/* Anto426-Rofi-Dynamic userChrome.css - Generated by wallpaper_effects.sh */

:root {
  --zen-colors-primary: rgba(116, 120, 163, 0.30) !important;
  --zen-primary-color: $accent !important;
  --zen-colors-secondary: rgba(116, 120, 163, 0.30) !important;
  --zen-colors-tertiary: rgba(73, 72, 99, 0.30) !important;
  --zen-colors-border: $accent !important;
  --toolbarbutton-icon-fill: $accent !important;
  --lwt-text-color: $foreground !important;
  --toolbar-field-color: $foreground !important;
  --tab-selected-textcolor: $selected_fg !important;
  --toolbar-field-focus-color: $foreground !important;
  --toolbar-color: $foreground !important;
  --newtab-text-primary-color: $foreground !important;
  --arrowpanel-color: $foreground !important;
  --arrowpanel-background: $(hex_to_css_rgba "$base" 0.62) !important;
  --sidebar-text-color: $foreground !important;
  --lwt-sidebar-text-color: $foreground !important;
  --lwt-sidebar-background-color: $(hex_to_css_rgba "$background" 0.62) !important;
  --toolbar-bgcolor: $(hex_to_css_rgba "$base" 0.62) !important;
  --newtab-background-color: $(hex_to_css_rgba "$background" 0.62) !important;
  --zen-themed-toolbar-bg: $(hex_to_css_rgba "$background" 0.62) !important;
  --zen-main-browser-background: $(hex_to_css_rgba "$background" 0.62) !important;
  --toolbox-bgcolor-inactive: $(hex_to_css_rgba "$background" 0.62) !important;
}

#permissions-granted-icon {
  color: $(hex_to_css_rgba "$background" 0.62) !important;
}

.sidebar-placesTree {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
}

#zen-workspaces-button {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
}

#TabsToolbar {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
}
.urlbar-background {
  background-color: $(hex_to_css_rgba "$base" 0.62) !important;
}

#urlbar[open] .urlbar-background,
#urlbar[breakout-extend] .urlbar-background,
.urlbarView {
  background-color: $(hex_to_css_rgba "$base" 0.95) !important;
}

.content-shortcuts {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
  border-color: $accent !important;
}

.urlbarView-url {
  color: $accent !important;
}

#zenEditBookmarkPanelFaviconContainer {
  background: $(hex_to_css_rgba "$background" 0.62) !important;
}

#zen-media-controls-toolbar {
  & #zen-media-progress-bar {
    &::-moz-range-track {
      background: $(hex_to_css_rgba "$base" 0.62) !important;
    }
  }
}

toolbar .toolbarbutton-1 {
  &:not([disabled]) {
    &:is([open], [checked])
      > :is(
        .toolbarbutton-icon,
        .toolbarbutton-text,
        .toolbarbutton-badge-stack
      ) {
      fill: $(hex_to_css_rgba "$background" 0.62) !important;
    }
  }
}

hbox#titlebar {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
}

#zen-appcontent-navbar-container {
  background-color: $(hex_to_css_rgba "$background" 0.62) !important;
}
EOF

    cat >"$temp_content" <<EOF
/* Anto426-Rofi-Dynamic userContent.css - Generated by wallpaper_effects.sh */

/* Common variables affecting all pages */
@-moz-document url-prefix("about:") {
  :root {
    --in-content-page-color: $foreground !important;
    --color-accent-primary: $accent !important;
    --color-accent-primary-hover: $accent !important;
    --color-accent-primary-active: $accent !important;
    background-color: $(hex_to_css_rgba "$background" 0.62) !important;
    --in-content-page-background: $(hex_to_css_rgba "$background" 0.62) !important;
  }
}

/* Variables and styles specific to about:newtab and about:home */
@-moz-document url("about:newtab"), url("about:home") {
  :root {
    --newtab-background-color: $(hex_to_css_rgba "$background" 0.62) !important;
    --newtab-background-color-secondary: $(hex_to_css_rgba "$base" 0.62) !important;
    --newtab-element-hover-color: $(hex_to_css_rgba "$base" 0.62) !important;
    --newtab-text-primary-color: $foreground !important;
    --newtab-wordmark-color: $foreground !important;
    --newtab-primary-action-background: $accent !important;
  }

  .icon {
    color: $accent !important;
  }

  .card-outer:is(:hover, :focus, .active):not(.placeholder) .card-title {
    color: $accent !important;
  }
}

/* Variables and styles specific to about:preferences */
@-moz-document url-prefix("about:preferences") {
  :root {
    --zen-colors-tertiary: $(hex_to_css_rgba "$background" 0.62) !important;
    --in-content-text-color: $foreground !important;
    --link-color: $accent !important;
    --link-color-hover: $accent !important;
    --zen-colors-primary: $(hex_to_css_rgba "$base" 0.62) !important;
    --in-content-box-background: $(hex_to_css_rgba "$base" 0.62) !important;
    --zen-primary-color: $accent !important;
  }

  groupbox, moz-card {
    background: $(hex_to_css_rgba "$base" 0.62) !important;
    border: 1px solid rgba(121, 123, 157, 0.15) !important;
    border-radius: 8px !important;
  }

  /* Style standard buttons inside settings cards and forms */
  groupbox button,
  moz-card button,
  #preferences-content button,
  #detail-box button,
  groupbox menulist {
    background: rgba(96, 96, 130, 0.18) !important;
    border: 1px solid rgba(121, 123, 157, 0.2) !important;
    color: $foreground !important;
    border-radius: 6px !important;
    padding: 6px 12px !important;
  }

  groupbox button:hover,
  moz-card button:hover,
  #preferences-content button:hover,
  #detail-box button:hover,
  groupbox menulist:hover {
    background: rgba(116, 120, 163, 0.30) !important;
    border-color: rgba(121, 123, 157, 0.4) !important;
  }

  /* Reset background for category sidebar selector buttons */
  #categories button.category,
  .navigation-list button,
  button.category-button,
  button.category {
    background: transparent !important;
    border: none !important;
    border-radius: 6px !important;
    opacity: 0.75 !important;
  }

  #categories button.category:hover,
  .navigation-list button:hover,
  button.category-button:hover,
  button.category:hover {
    background: rgba(116, 120, 163, 0.18) !important;
    opacity: 1 !important;
  }

  #categories button.category[selected="true"],
  #categories button.category.active,
  .navigation-list button[selected="true"],
  .navigation-list button.active,
  button.category-button[selected="true"],
  button.category-button.active,
  button.category[selected="true"],
  button.category.active {
    background: rgba(113, 130, 191, 0.34) !important;
    border-left: 3px solid $accent !important;
    opacity: 1 !important;
    font-weight: bold !important;
  }

  /* Style standard inputs */
  input,
  html|input,
  select,
  textbox {
    background: rgba(73, 72, 99, 0.30) !important;
    border: 1px solid rgba(121, 123, 157, 0.25) !important;
    color: $foreground !important;
    border-radius: 6px !important;
    padding: 6px 12px !important;
  }

  input:focus,
  html|input:focus,
  select:focus,
  textbox:focus {
    border-color: $accent !important;
    outline: none !important;
  }

  /* Style checkboxes */
  checkbox .checkbox-check {
    background: rgba(73, 72, 99, 0.30) !important;
    border: 1px solid rgba(121, 123, 157, 0.25) !important;
    border-radius: 4px !important;
  }

  checkbox[checked="true"] .checkbox-check {
    background: $accent !important;
    border-color: $accent !important;
    color: $selected_fg !important;
  }

  /* Style the search box and container */
  #search-container {
    background-color: transparent !important;
  }

  #searchInput {
    --input-text-background-color: $(hex_to_css_rgba "$base_alt" 0.30) !important;
    --input-text-border-color: $(hex_to_css_rgba "$border" 0.25) !important;
    --input-text-color: $foreground !important;
    --input-text-border-radius: 6px !important;

    background: $(hex_to_css_rgba "$base_alt" 0.30) !important;
    border: 1px solid $(hex_to_css_rgba "$border" 0.25) !important;
    color: $foreground !important;
    border-radius: 6px !important;
  }

  #searchInput:focus,
  #searchInput:focus-within {
    --input-text-border-color: $accent !important;
    border-color: $accent !important;
    outline: none !important;
  }

  /* Style the policies container banner */
  #policies-container,
  #policies-container-content {
    --nav-notice-background-color: $(hex_to_css_rgba "$base" 0.30) !important;
    --nav-notice-text-color: $foreground !important;

    background: $(hex_to_css_rgba "$base" 0.30) !important;
    border: 1px solid $(hex_to_css_rgba "$border" 0.25) !important;
    color: $foreground !important;
    border-radius: 8px !important;
    margin-bottom: 8px !important;
  }

  #policies-container *,
  #policies-container-content * {
    color: inherit !important;
  }

  .main-content {
    background-color: $(hex_to_css_rgba "$background" 0.62) !important;
  }
}
EOF

    local profile_dir
    local chrome_dir

    for profile_dir in "$zen_dir"/*Profile "$zen_dir"/*.Default*; do
        [[ -d "$profile_dir" ]] || continue
        chrome_dir="$profile_dir/chrome"
        mkdir -p "$chrome_dir"
        if ! cmp -s "$temp_chrome" "$chrome_dir/userChrome.css"; then
            cp "$temp_chrome" "$chrome_dir/userChrome.css"
        fi
        if ! cmp -s "$temp_content" "$chrome_dir/userContent.css"; then
            cp "$temp_content" "$chrome_dir/userContent.css"
        fi

        local user_js="$profile_dir/user.js"
        local prefs=(
            'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
            'user_pref("zen.widget.linux.transparency", true);'
            'user_pref("browser.tabs.allow_transparent_browser", true);'
            'user_pref("widget.transparent-windows", true);'
        )
        local pref
        for pref in "${prefs[@]}"; do
            if [[ ! -f "$user_js" ]]; then
                echo "$pref" > "$user_js"
            elif ! grep -qF "$pref" "$user_js"; then
                echo "$pref" >> "$user_js"
            fi
        done
    done
}

write_app_theme() {
    # Scrittura dei temi per le app in parallelo
    write_icon_theme &
    pid_icons=$!
    write_gtk_theme &
    pid_gtk=$!
    write_qt_theme &
    pid_qt=$!
    write_zen_theme &
    pid_zen=$!

    wait $pid_icons $pid_gtk $pid_qt $pid_zen

    if declare -F effects_job_is_stale >/dev/null 2>&1 && effects_job_is_stale; then
        log "Skipping stale GTK/Qt reload after app theme write"
        return 0
    fi

    # Ricarica dei temi in parallelo
    gtk_reload_theme &
    pid_gtk_reload=$!
    qt_reload_theme &
    pid_qt_reload=$!

    wait $pid_gtk_reload $pid_qt_reload
}
