#!/usr/bin/env bash
# Palette generation from wallpaper RGB samples.
# Outputs semantic tokens consumed by Hyprland, Rofi, GTK, Ghostty, GRUB, SDDM.

generate_palette_from_samples() {
    local r="$1"
    local g="$2"
    local b="$3"
    local ar="$4"
    local ag="$5"
    local ab="$6"

    local core="${ANTO426_WALLPAPER_CORE_BIN:-$script_dir/wallpaper_core}"
    local values
    [[ -x "$core" ]] || { log "Compiled palette provider unavailable: $core"; return 1; }
    values="$("$core" palette-samples "$r" "$g" "$b" "$ar" "$ag" "$ab")" || return 1
    # Only the compiled provider formats these assignments from validated RGB.
    source /dev/stdin <<<"$values"

    panel_bg="$(hex_to_rofi_rgba "$background" 62)"
    panel_bg_hover="$(hex_to_rofi_rgba "$background" 78)"
    overlay_bg="$(hex_to_rofi_rgba "$background" 28)"
    item_bg="$(hex_to_rofi_rgba "$surface" 18)"
    item_bg_hover="$(hex_to_rofi_rgba "$select" 30)"
    item_bg_active="$(hex_to_rofi_rgba "$select" 42)"
    accent_soft="$(hex_to_rofi_rgba "$accent" 22)"
    accent_strong="$(hex_to_rofi_rgba "$accent" 42)"
    border_soft="$(hex_to_rofi_rgba "$border" 16)"
    border_medium="$(hex_to_rofi_rgba "$border" 34)"
    shadow_soft="$(hex_to_rofi_rgba "$background" 18)"
    shadow_medium="$(hex_to_rofi_rgba "$background" 30)"

    background_alpha="$panel_bg"
    surface_alpha="$item_bg"
    select_alpha="$item_bg_active"
    accent_alpha="$accent_strong"
    border_alpha="$border_medium"
}

write_palette_map() {
    local map_file="${1:-$state_dir/palette.map}"
    [[ -n "${state_dir:-}" ]] || return 0

    mkdir -p "$(dirname "$map_file")"
    cat >"$map_file" <<EOF
# Generated by wallpaper_effects.sh — palette routing map
# wallpaper=$current_wallpaper_path

[core]
background=$background
surface=$surface
base=$base
base_alt=$base_alt
foreground=$foreground
muted=$muted
accent=$accent
select=$select
border=$border
selected_fg=$selected_fg

[semantic]
titlebar=$titlebar
titlebar_backdrop=$titlebar_backdrop
popover=$popover
red=$red
orange=$orange
yellow=$yellow
green=$green
pink=$pink
purple=$purple
gray=$gray

[targets.session]
hypr=$hypr_theme_file
colors=$colors_dir/colors.{css,rasi,sh}
ghostty=$ghostty_dynamic_file
vscode=$vscode_theme_file
htop=$HOME/.config/htop/htoprc

[targets.apps]
gtk3=$gtk3_dir/gtk.css
gtk4=$gtk4_dir/gtk.css
qt5ct=$qt5ct_dir/colors/anto426.conf
qt6ct=$qt6ct_dir/colors/anto426.conf
kvantum=$kvantum_theme_dir

[domain.boot-login]
state=${local_config_root:-${XDG_CONFIG_HOME:-$HOME/.config}/anto426-local}/wallpaper/boot-login.env
policy=isolated-explicit-target

[htop.tokens]
color_scheme=0
source=terminal-ansi-palette
EOF
}
