#!/usr/bin/env bash


write_color_files() {
    local colors_css_tmp="$colors_dir/.colors.css.tmp.$$"
    local colors_rasi_tmp="$colors_dir/.colors.rasi.tmp.$$"
    local colors_sh_tmp="$colors_dir/.colors.sh.tmp.$$"

    cat >"$colors_css_tmp" <<EOF
@define-color background $background;
@define-color surface    $surface;
@define-color base       $base;
@define-color base-alt   $base_alt;
@define-color titlebar   $titlebar;
@define-color titlebar-backdrop $titlebar_backdrop;
@define-color popover    $popover;
@define-color foreground $foreground;
@define-color muted      $muted;
@define-color select     $select;
@define-color accent     $accent;
@define-color selected-fg $selected_fg;
@define-color border     $border;

@define-color panel-bg         $(hex_to_css_rgba "$background" 0.62);
@define-color panel-bg-hover   $(hex_to_css_rgba "$background" 0.78);
@define-color overlay-bg       $(hex_to_css_rgba "$background" 0.28);
@define-color item-bg          $(hex_to_css_rgba "$surface" 0.18);
@define-color item-bg-hover    $(hex_to_css_rgba "$select" 0.30);
@define-color item-bg-active   $(hex_to_css_rgba "$select" 0.42);
@define-color accent-soft      $(hex_to_css_rgba "$accent" 0.22);
@define-color accent-strong    $(hex_to_css_rgba "$accent" 0.42);
@define-color border-soft      $(hex_to_css_rgba "$border" 0.16);
@define-color border-medium    $(hex_to_css_rgba "$border" 0.34);
@define-color shadow-soft      $(hex_to_css_rgba "$background" 0.18);
@define-color shadow-medium    $(hex_to_css_rgba "$background" 0.30);

@define-color background-alpha @panel-bg;
@define-color surface-alpha    @item-bg;
@define-color select-alpha     @item-bg-active;
@define-color accent-alpha     @accent-strong;
@define-color border-alpha     @border-medium;

@define-color pink       $pink;
@define-color purple     $purple;
@define-color red        $red;
@define-color orange     $orange;
@define-color yellow     $yellow;
@define-color green      $green;
@define-color blue       @accent;
@define-color cyan       @muted;
@define-color gray       $gray;
EOF

    cat >"$colors_rasi_tmp" <<EOF
* {
    background: $background;
    surface: $surface;
    base: $base;
    base-alt: $base_alt;
    titlebar: $titlebar;
    titlebar-backdrop: $titlebar_backdrop;
    popover: $popover;
    panel-bg: $panel_bg;
    panel-bg-hover: $panel_bg_hover;
    overlay-bg: $overlay_bg;
    item-bg: $item_bg;
    item-bg-hover: $item_bg_hover;
    item-bg-active: $item_bg_active;
    accent-soft: $accent_soft;
    accent-strong: $accent_strong;
    border-soft: $border_soft;
    border-medium: $border_medium;
    shadow-soft: $shadow_soft;
    shadow-medium: $shadow_medium;
    background-alpha: $background_alpha;
    surface-alpha: $surface_alpha;
    foreground: $foreground;
    muted: $muted;
    select: $select;
    select-alpha: $select_alpha;

    accent: $accent;
    selected-fg: $selected_fg;
    accent-alpha: $accent_alpha;
    border: $border;
    border-alpha: $border_alpha;
    pink: $pink;
    purple: $purple;
    red: $red;
    orange: $orange;
    yellow: $yellow;
    green: $green;
    blue: @accent;
    cyan: @muted;
    gray: $gray;

    active-background: @select;
    urgent-background: @red;
    urgent-foreground: @background;
    selected-background: @accent;
    selected-urgent-background: @urgent-background;
    selected-active-background: @active-background;
    bordercolor: @border;
}
EOF

    cat >"$colors_sh_tmp" <<EOF
# Generated by wallpaper_effects.sh
export ANTO426_BACKGROUND="$background"
export ANTO426_SURFACE="$surface"
export ANTO426_BASE="$base"
export ANTO426_BASE_ALT="$base_alt"
export ANTO426_TITLEBAR="$titlebar"
export ANTO426_TITLEBAR_BACKDROP="$titlebar_backdrop"
export ANTO426_POPOVER="$popover"
export ANTO426_FOREGROUND="$foreground"
export ANTO426_MUTED="$muted"
export ANTO426_SELECT="$select"
export ANTO426_ACCENT="$accent"
export ANTO426_SELECTED_FG="$selected_fg"
export ANTO426_BORDER="$border"
export ANTO426_PANEL_BG="$(hex_to_css_rgba "$background" 0.62)"
export ANTO426_PANEL_BG_HOVER="$(hex_to_css_rgba "$background" 0.78)"
export ANTO426_OVERLAY_BG="$(hex_to_css_rgba "$background" 0.28)"
export ANTO426_ITEM_BG="$(hex_to_css_rgba "$surface" 0.18)"
export ANTO426_ITEM_BG_HOVER="$(hex_to_css_rgba "$select" 0.30)"
export ANTO426_ITEM_BG_ACTIVE="$(hex_to_css_rgba "$select" 0.42)"
export ANTO426_ACCENT_SOFT="$(hex_to_css_rgba "$accent" 0.22)"
export ANTO426_ACCENT_STRONG="$(hex_to_css_rgba "$accent" 0.42)"
export ANTO426_BORDER_SOFT="$(hex_to_css_rgba "$border" 0.16)"
export ANTO426_BORDER_MEDIUM="$(hex_to_css_rgba "$border" 0.34)"
export ANTO426_SHADOW_SOFT="$(hex_to_css_rgba "$background" 0.18)"
export ANTO426_SHADOW_MEDIUM="$(hex_to_css_rgba "$background" 0.30)"
export ANTO426_WALLPAPER="$current_wallpaper_path"
EOF

    chmod 0644 "$colors_css_tmp" "$colors_rasi_tmp" "$colors_sh_tmp"
    mv -f -- "$colors_css_tmp" "$colors_dir/colors.css"
    mv -f -- "$colors_rasi_tmp" "$colors_dir/colors.rasi"
    mv -f -- "$colors_sh_tmp" "$colors_dir/colors.sh"
}

write_hypr_theme() {
    local temporary="$hypr_theme_file.tmp.$$"

    cat >"$temporary" <<EOF
# Generated by wallpaper_effects.sh
\$anto426_wallpaper = $destination_wallpaper_dir/normal.png
\$anto426_background = $(hypr_rgb "$background")
\$anto426_surface = $(hypr_rgb "$surface")
\$anto426_foreground = $(hypr_rgb "$foreground")
\$anto426_muted = $(hypr_rgb "$muted")
\$anto426_accent = $(hypr_rgb "$accent")
\$anto426_border = $(hypr_rgb "$border")
\$anto426_muted_hex = $muted

\$anto426_active_border = $(hypr_rgba "$accent" ee)
\$anto426_inactive_border = $(hypr_rgba "$background" aa)
\$anto426_shadow = rgba(00000055)
\$anto426_panel_bg = $(hypr_rgba "$background" 75)
\$anto426_panel_bg_hover = $(hypr_rgba "$background" c7)
\$anto426_overlay_bg = $(hypr_rgba "$background" 47)
\$anto426_item_bg = $(hypr_rgba "$surface" 2e)
\$anto426_item_bg_hover = $(hypr_rgba "$select" 4d)
\$anto426_item_bg_active = $(hypr_rgba "$select" 6b)
\$anto426_border_medium = $(hypr_rgba "$border" 57)
\$anto426_shadow_soft = $(hypr_rgba "$background" 2e)
\$anto426_shadow_medium = $(hypr_rgba "$background" 4d)
\$anto426_background_panel = $(hypr_rgba "$background" cc)
\$anto426_background_soft = $(hypr_rgba "$background" 99)
\$anto426_surface_panel = $(hypr_rgba "$surface" c7)
\$anto426_border_panel = $(hypr_rgba "$foreground" 35)
\$anto426_foreground_strong = $(hypr_rgba "$foreground" e6)
\$anto426_accent_strong = $(hypr_rgba "$accent" f2)
\$anto426_accent_soft = $(hypr_rgba "$accent" cc)
\$anto426_surface_soft = $(hypr_rgba "$foreground" 11)
\$anto426_border_soft = $(hypr_rgba "$border" 66)
\$anto426_error = $(hypr_rgb "$red")
\$anto426_warning = $(hypr_rgb "$yellow")
\$anto426_success = $(hypr_rgb "$green")
EOF

    chmod 0644 "$temporary"
    mv -f -- "$temporary" "$hypr_theme_file"
}

write_terminal_theme() {
    # The named Ghostty theme is a static fallback. Runtime colors live only
    # in the machine-local include so wallpaper changes never rewrite dotfiles.
    # Ghostty watches all loaded config files, so writing here triggers hot-reload.
    cat >"$ghostty_dynamic_file" <<EOF
# Generated by wallpaper_effects.sh at $(date '+%Y-%m-%dT%H:%M:%S')
palette = 0=${background#\#}
palette = 1=${red#\#}
palette = 2=${green#\#}
palette = 3=${yellow#\#}
palette = 4=${accent#\#}
palette = 5=${pink#\#}
palette = 6=${muted#\#}
palette = 7=${foreground#\#}
palette = 8=${gray#\#}
palette = 9=${red#\#}
palette = 10=${green#\#}
palette = 11=${yellow#\#}
palette = 12=${accent#\#}
palette = 13=${purple#\#}
palette = 14=${muted#\#}
palette = 15=ffffff
background = ${background#\#}
foreground = ${foreground#\#}
cursor-color = ${accent#\#}
cursor-text = ${background#\#}
selection-background = ${select#\#}
selection-foreground = ${foreground#\#}
EOF
}

write_htop_theme() {
    local target="$htop_config_dir/htoprc"
    local htop_version
    local tmp

    mkdir -p "$htop_config_dir"
    htop_version="$(htop --version 2>/dev/null | awk 'NR == 1 { print $2; exit }')"
    htop_version="${htop_version:-3.5.1}"

    if [[ -f "$target" ]]; then
        tmp="$(mktemp)"
        awk '
            BEGIN {
                seen_color = 0
                seen_base = 0
                seen_megabytes = 0
            }
            /^color_scheme=/ {
                print "color_scheme=0"
                seen_color = 1
                next
            }
            /^highlight_base_name=/ {
                print "highlight_base_name=1"
                seen_base = 1
                next
            }
            /^highlight_megabytes=/ {
                print "highlight_megabytes=1"
                seen_megabytes = 1
                next
            }
            { print }
            END {
                if (!seen_color) print "color_scheme=0"
                if (!seen_base) print "highlight_base_name=1"
                if (!seen_megabytes) print "highlight_megabytes=1"
            }
        ' "$target" >"$tmp"
        mv "$tmp" "$target"
        log "htop palette aggiornata: $target"
        return 0
    fi

    cat >"$target" <<EOF
# Generated by wallpaper_effects.sh
# htop reads ANSI colors from the terminal; color_scheme=0 lets Ghostty's
# dynamic wallpaper palette drive the UI.
htop_version=$htop_version
config_reader_min_version=3
fields=0 48 17 18 38 39 130 2 46 47 49 1
hide_kernel_threads=1
hide_userland_threads=0
hide_running_in_container=0
shadow_other_users=1
show_thread_names=0
show_program_path=1
highlight_base_name=1
highlight_deleted_exe=1
shadow_distribution_path_prefix=0
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
header_margin=1
screen_tabs=1
detailed_cpu_time=0
cpu_count_from_one=1
show_cpu_usage=1
show_cpu_frequency=1
show_cpu_temperature=1
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
hide_function_bar=0
header_layout=two_50_50
column_meters_0=LeftCPUs Memory Swap
column_meter_modes_0=1 1 1
column_meters_1=RightCPUs Tasks LoadAverage Uptime
column_meter_modes_1=1 2 2 2
tree_view=0
sort_key=46
tree_sort_key=0
sort_direction=-1
tree_sort_direction=1
tree_view_always_by_pid=0
all_branches_collapsed=0
screen:Main=PID USER PRIORITY NICE M_VIRT M_RESIDENT M_PRIV STATE PERCENT_CPU PERCENT_MEM TIME Command
.sort_key=PERCENT_CPU
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
screen:I/O=PID USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE PERCENT_SWAP_DELAY PERCENT_IO_DELAY Command
.sort_key=IO_RATE
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
EOF

    log "htop palette creata: $target"
}

write_btop_theme() {
    local config="$btop_config_dir/btop.conf"
    local theme="$btop_theme_dir/anto426.theme"
    local tmp

    mkdir -p "$btop_theme_dir"
    cat >"$theme" <<EOF
# Generated by wallpaper_effects.sh
theme[main_bg]="$background"
theme[main_fg]="$foreground"
theme[title]="$foreground"
theme[hi_fg]="$accent"
theme[selected_bg]="$select"
theme[selected_fg]="$selected_fg"
theme[inactive_fg]="$muted"
theme[proc_misc]="$accent"
theme[cpu_box]="$border"
theme[mem_box]="$border"
theme[net_box]="$border"
theme[proc_box]="$border"
theme[div_line]="$border"
theme[temp_start]="$green"
theme[temp_mid]="$yellow"
theme[temp_end]="$red"
theme[cpu_start]="$green"
theme[cpu_mid]="$yellow"
theme[cpu_end]="$red"
theme[free_start]="$green"
theme[free_mid]="$yellow"
theme[free_end]="$red"
theme[cached_start]="$muted"
theme[cached_mid]="$accent"
theme[cached_end]="$purple"
theme[available_start]="$green"
theme[available_mid]="$accent"
theme[available_end]="$purple"
theme[used_start]="$green"
theme[used_mid]="$yellow"
theme[used_end]="$red"
theme[download_start]="$green"
theme[download_mid]="$accent"
theme[download_end]="$purple"
theme[upload_start]="$pink"
theme[upload_mid]="$orange"
theme[upload_end]="$red"
EOF

    if [[ -f "$config" ]]; then
        tmp="$(mktemp)"
        awk '
            BEGIN {
                seen_theme = 0
                seen_background = 0
                seen_truecolor = 0
            }
            /^[[:space:]]*color_theme[[:space:]]*=/ {
                print "color_theme = \"anto426\""
                seen_theme = 1
                next
            }
            /^[[:space:]]*theme_background[[:space:]]*=/ {
                print "theme_background = false"
                seen_background = 1
                next
            }
            /^[[:space:]]*truecolor[[:space:]]*=/ {
                print "truecolor = true"
                seen_truecolor = 1
                next
            }
            { print }
            END {
                if (!seen_theme) print "color_theme = \"anto426\""
                if (!seen_background) print "theme_background = false"
                if (!seen_truecolor) print "truecolor = true"
            }
        ' "$config" >"$tmp"
        mv "$tmp" "$config"
    else
        cat >"$config" <<EOF
# Generated by wallpaper_effects.sh
color_theme = "anto426"
theme_background = false
truecolor = true
rounded_corners = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_colors = true
proc_gradient = true
proc_cpu_graphs = true
check_temp = true
show_coretemp = true
show_cpu_freq = true
show_uptime = true
mem_graphs = true
show_disks = true
net_auto = true
EOF
    fi

    log "btop palette aggiornata: $theme"
}

write_session_theme() {
    # Scrittura dei file di configurazione in parallelo
    write_color_files &
    write_hypr_theme &
    write_terminal_theme &
    [[ "${ANTO426_WALLPAPER_CORE_VSCODE:-1}" != "0" ]] && write_vscode_theme &
    [[ "${ANTO426_WALLPAPER_CORE_OBSIDIAN:-1}" != "0" ]] && write_obsidian_theme &
    write_htop_theme &
    write_btop_theme &
    write_palette_map "$state_dir/palette.map" &
    
    wait
}
