#!/usr/bin/env bash

gtk_theme_exists() {
    local theme="$1"

    [[ -d "$HOME/.themes/$theme" ]] ||
        [[ -d "$HOME/.local/share/themes/$theme" ]] ||
        [[ -d "/usr/share/themes/$theme" ]]
}

gtk_reload_theme() {
    local target_theme="${gtk_theme_name:-adw-gtk3-dark}"

    command -v gsettings >/dev/null 2>&1 || return 0

    # Force immediate reload in running GTK3/GTK4 apps by bouncing the theme and color scheme
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface color-scheme "default" 2>/dev/null || true
    sleep 0.1

    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface gtk-theme "$target_theme" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-dark" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface cursor-theme "macOS" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface font-name "Segoe UI Variable Static Text 12" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMono Nerd Font 12" 2>/dev/null || true
}

restart_gtk_portals() {
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --user restart \
            xdg-desktop-portal-gtk.service \
            xdg-desktop-portal.service \
            xdg-desktop-portal-hyprland.service >/dev/null 2>&1 && return 0
    fi

    pkill -x xdg-desktop-portal-gtk 2>/dev/null || true
    pkill -x xdg-desktop-portal 2>/dev/null || true
}

write_gtk_css_file() {
    local output="$1"
    local gtk_major="$2"
    local base_css="${3:-}"

    {
        printf '/* Generated by wallpaper_effects.sh for GTK %s */\n' "$gtk_major"
        [[ -n "$base_css" ]] && printf '@import url("%s");\n\n' "$base_css"
        cat <<EOF
/* GTK 3 & 4 Named Colors */
@define-color theme_fg_color $foreground;
@define-color theme_text_color $foreground;
@define-color theme_bg_color $background;
@define-color theme_base_color $background;
@define-color theme_selected_bg_color $accent;
@define-color theme_selected_fg_color $background;
@define-color borders $border;

@define-color insensitive_bg_color $background;
@define-color insensitive_fg_color $muted;
@define-color insensitive_base_color $surface;

@define-color theme_unfocused_fg_color $foreground;
@define-color theme_unfocused_text_color $foreground;
@define-color theme_unfocused_bg_color $background;
@define-color theme_unfocused_base_color $background;
@define-color theme_unfocused_selected_bg_color $select;
@define-color theme_unfocused_selected_fg_color $foreground;
@define-color unfocused_insensitive_color $muted;
@define-color unfocused_borders $border;

@define-color wm_title $foreground;
@define-color wm_unfocused_title $muted;
@define-color wm_bg $surface;
@define-color wm_unfocused_bg $background;

/* Libadwaita / GTK4 compatibility colors */
@define-color accent_bg_color $accent;
@define-color accent_fg_color $background;
@define-color accent_color $accent;
@define-color destructive_bg_color $red;
@define-color destructive_fg_color $background;
@define-color success_bg_color $green;
@define-color success_fg_color $background;
@define-color warning_bg_color $orange;
@define-color warning_fg_color $background;
@define-color error_bg_color $red;
@define-color error_fg_color $background;

@define-color window_bg_color $background;
@define-color window_fg_color $foreground;
@define-color view_bg_color $background;
@define-color view_fg_color $foreground;

@define-color headerbar_bg_color $surface;
@define-color headerbar_fg_color $foreground;
@define-color headerbar_border_color $border;
@define-color headerbar_backdrop_color $background;
@define-color headerbar_shade_color $border;

@define-color card_bg_color $surface;
@define-color card_fg_color $foreground;
@define-color card_shade_color $border;

@define-color dialog_bg_color $surface;
@define-color dialog_fg_color $foreground;

@define-color popover_bg_color $surface;
@define-color popover_fg_color $foreground;

@define-color shade_color $border;
@define-color scrollbar_outline_color $border;

* {
  caret-color: @accent_color;
}
EOF
    } >"$output"
}

find_gtk_base_theme() {
    local theme="${ANTO426_GTK_BASE_THEME:-Anto426-Dark}"
    local candidate

    for candidate in \
        "$HOME/.themes/$theme" \
        "$HOME/.local/share/themes/$theme" \
        "/usr/share/themes/$theme" \
        "$HOME/.themes/Anto426" \
        "$HOME/.local/share/themes/Anto426" \
        "/usr/share/themes/Anto426"; do
        if [[ -d "$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done

    return 1
}

copy_gtk_base_theme() {
    local target="$1"
    local base_theme

    rm -rf "$target"
    mkdir -p "$(dirname "$target")"

    if base_theme="$(find_gtk_base_theme)"; then
        cp -a "$base_theme" "$target"
        return 0
    fi

    mkdir -p "$target/gtk-3.0" "$target/gtk-4.0"
    return 1
}

# Convert a hex color like #aabbcc to decimal "r, g, b" for rgba() replacement
hex_to_rgb_triple() {
    local hex="${1#\#}"
    printf '%d, %d, %d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# Patch all hardcoded colors (hex and rgba) in a compiled GTK CSS file
patch_gtk_base_css() {
    local file="$1"
    [[ -f "$file" ]] || return 0

    # Original theme hardcoded colors (Anto426-Dark / Orchis purple palette)
    local orig_accent="9579b6"       # purple accent
    local orig_bg="281f33"           # deep purple bg
    local orig_surface="342941"      # dark purple surface
    local orig_mid="635575"          # mid purple (buttons, entries bg)
    local orig_mid2="817190"         # light purple (borders/shadows)
    local orig_muted="b9c4d2"        # muted text (stays the same, it's neutral)
    local orig_fg="f6f7fb"           # foreground

    # Compute RGB triples for rgba() replacement
    local rgb_accent; rgb_accent="$(hex_to_rgb_triple "$accent")"
    local rgb_bg;     rgb_bg="$(hex_to_rgb_triple "$background")"
    local rgb_surface; rgb_surface="$(hex_to_rgb_triple "$surface")"
    local rgb_border; rgb_border="$(hex_to_rgb_triple "$border")"
    local rgb_muted;  rgb_muted="$(hex_to_rgb_triple "$muted")"
    local rgb_fg;     rgb_fg="$(hex_to_rgb_triple "$foreground")"

    # Original RGB triples (from the Anto426-Dark compiled values)
    local orig_rgb_accent="149, 121, 182"
    local orig_rgb_bg="40, 31, 51"
    local orig_rgb_surface="52, 41, 65"
    local orig_rgb_mid="99, 85, 117"
    local orig_rgb_mid2="129, 117, 144"
    local orig_rgb_muted="185, 196, 210"

    sed -i \
        -e "s/#${orig_accent}/${accent}/gI" \
        -e "s/#${orig_bg}/${background}/gI" \
        -e "s/#${orig_surface}/${surface}/gI" \
        -e "s/#${orig_mid}/${surface}/gI" \
        -e "s/#${orig_mid2}/${border}/gI" \
        -e "s/#${orig_fg}/${foreground}/gI" \
        -e "s/rgba(${orig_rgb_accent},/rgba(${rgb_accent},/g" \
        -e "s/rgba(${orig_rgb_bg},/rgba(${rgb_bg},/g" \
        -e "s/rgba(${orig_rgb_surface},/rgba(${rgb_surface},/g" \
        -e "s/rgba(${orig_rgb_mid},/rgba(${rgb_surface},/g" \
        -e "s/rgba(${orig_rgb_mid2},/rgba(${rgb_border},/g" \
        -e "s/rgba(${orig_rgb_muted},/rgba(${rgb_muted},/g" \
        "$file" 2>/dev/null || true
}

prepare_gtk_overlay_target() {
    local target="$1"
    local gtk_dir="$2"
    local css_dir="$target/$gtk_dir"
    local base_css="base.css"
    local base_dark_css="base-dark.css"

    mkdir -p "$css_dir"

    if [[ -f "$css_dir/gtk.css" ]]; then
        mv "$css_dir/gtk.css" "$css_dir/$base_css"
    else
        base_css=""
    fi

    if [[ -f "$css_dir/gtk-dark.css" ]]; then
        mv "$css_dir/gtk-dark.css" "$css_dir/$base_dark_css"
    else
        base_dark_css="$base_css"
    fi

    # Patch hardcoded hex AND rgba() colors in the compiled base theme files
    [[ -n "$base_css" ]] && patch_gtk_base_css "$css_dir/$base_css"
    [[ -n "$base_dark_css" && "$base_dark_css" != "$base_css" ]] && patch_gtk_base_css "$css_dir/$base_dark_css"

    write_gtk_css_file "$css_dir/gtk.css" "${gtk_dir#gtk-}" "$base_css"
    write_gtk_css_file "$css_dir/gtk-dark.css" "${gtk_dir#gtk-}" "$base_dark_css"
}

write_gtk_theme() {
    local theme_root
    local theme_share_root
    local target

    gtk_theme_name="anto426"
    theme_root="$HOME/.themes/$gtk_theme_name"
    theme_share_root="$HOME/.local/share/themes/$gtk_theme_name"

    mkdir -p "$HOME/.themes" "$HOME/.local/share/themes"

    for target in "$theme_root" "$theme_share_root"; do
        copy_gtk_base_theme "$target" || true
        prepare_gtk_overlay_target "$target" "gtk-3.0"
        prepare_gtk_overlay_target "$target" "gtk-4.0"
        cat >"$target/index.theme" <<EOF
[X-GNOME-Metatheme]
Name=$gtk_theme_name
Type=X-GNOME-Metatheme
Comment=Dynamic anto426 GTK theme based on Anto426-theme
Encoding=UTF-8
GtkTheme=$gtk_theme_name
EOF
    done

    write_gtk_css_file "$gtk3_dir/gtk.css" "3.0"
    write_gtk_css_file "$gtk4_dir/gtk.css" "4.0"

    for gtk_settings_dir in "$gtk3_dir" "$gtk4_dir"; do
        cat >"$gtk_settings_dir/settings.ini" <<EOF
[Settings]
gtk-theme-name=$gtk_theme_name
gtk-icon-theme-name=WhiteSur-dark
gtk-cursor-theme-name=macOS
gtk-font-name=Segoe UI Variable Static Text 12
gtk-application-prefer-dark-theme=true
EOF
    done
}

write_qt_theme() {
    local qt_fg qt_bg qt_surface qt_select qt_accent qt_border qt_muted qt_red qt_purple qt_shadow
    local qt_active_colors qt_disabled_colors qt_inactive_colors qt_dir

    qt_fg="$(qt_argb "$foreground")"
    qt_bg="$(qt_argb "$background")"
    qt_surface="$(qt_argb "$surface")"
    qt_select="$(qt_argb "$select")"
    qt_accent="$(qt_argb "$accent")"
    qt_border="$(qt_argb "$border")"
    qt_muted="$(qt_argb "$muted")"
    qt_red="$(qt_argb "$red")"
    qt_purple="$(qt_argb "$purple")"
    qt_shadow="$(qt_argb "$background" 80)"
    qt_active_colors="$qt_fg, $qt_surface, $qt_select, $qt_border, $qt_bg, $qt_surface, $qt_fg, $qt_fg, $qt_fg, $qt_bg, $qt_bg, $qt_shadow, $qt_accent, $qt_bg, $qt_accent, $qt_purple, $qt_surface, $qt_fg, $qt_surface, $qt_fg, $qt_shadow"
    qt_disabled_colors="$qt_muted, $qt_surface, $qt_select, $qt_border, $qt_bg, $qt_surface, $qt_muted, $qt_fg, $qt_muted, $qt_bg, $qt_bg, $qt_shadow, $qt_border, $qt_muted, $qt_accent, $qt_red, $qt_surface, $qt_fg, $qt_surface, $qt_muted, $qt_shadow"
    qt_inactive_colors="$qt_fg, $qt_surface, $qt_select, $qt_border, $qt_bg, $qt_surface, $qt_fg, $qt_fg, $qt_fg, $qt_bg, $qt_bg, $qt_shadow, $qt_accent, $qt_bg, $qt_accent, $qt_purple, $qt_surface, $qt_fg, $qt_surface, $qt_fg, $qt_shadow"

    for qt_dir in "$qt5ct_dir" "$qt6ct_dir"; do
        cat >"$qt_dir/colors/anto426.conf" <<EOF
[ColorScheme]
active_colors=$qt_active_colors
disabled_colors=$qt_disabled_colors
inactive_colors=$qt_inactive_colors
EOF

        cat >"$qt_dir/anto426.qss" <<EOF
QToolTip {
  background-color: $surface;
  color: $foreground;
  border: 1px solid $border;
  border-radius: 6px;
}

QMenu, QMenuBar, QToolBar, QStatusBar {
  background-color: $background;
  color: $foreground;
  border: none;
}

QMenu::item:selected {
  background-color: $accent;
  color: $background;
}
EOF
    done

    cat >"$qt5ct_dir/qt5ct.conf" <<EOF
[Appearance]
color_scheme_path=$qt5ct_dir/colors/anto426.conf
custom_palette=true
icon_theme=WhiteSur-dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="JetBrainsMono Nerd Font,12,-1,5,50,0,0,0,0,0"
general="Segoe UI Variable Static Text,12,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
gui_effects=@Invalid()
menus_have_icons=true
stylesheets=$qt5ct_dir/anto426.qss
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
EOF

    cat >"$qt6ct_dir/qt6ct.conf" <<EOF
[Appearance]
color_scheme_path=$qt6ct_dir/colors/anto426.conf
custom_palette=true
icon_theme=WhiteSur-dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="JetBrainsMono Nerd Font,12,-1,5,50,0,0,0,0,0"
general="Segoe UI Variable Static Text,12,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
gui_effects=@Invalid()
menus_have_icons=true
stylesheets=$qt6ct_dir/anto426.qss
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
EOF
}

write_kvantum_theme() {
    local k_theme="anto426"
    local k_dir="$kvantum_dir/$k_theme"
    local base_svg="/usr/share/Kvantum/KvArcDark/KvArcDark.svg"
    local base_config="/usr/share/Kvantum/KvArcDark/KvArcDark.kvconfig"
    local use_base=0

    mkdir -p "$kvantum_dir" "$k_dir"
    find "$kvantum_dir" -maxdepth 1 -type d \
        -iname 'anto426*' \
        ! -name "$k_theme" -exec rm -rf {} + 2>/dev/null || true

    [[ -r "$base_svg" && -r "$base_config" ]] && use_base=1

    if ((use_base)); then
        awk \
            -v bg="$surface" \
            -v fg="$foreground" \
            -v border="$border" \
            -v accent="$accent" '
            /#404552/ { gsub(/#404552/, bg) }
            /#383c4a/ { gsub(/#383c4a/, bg) }
            /#4b5162/ { gsub(/#4b5162/, bg) }
            /#5294e2/ { gsub(/#5294e2/, accent) }
            /#d3dae3/ { gsub(/#d3dae3/, fg) }
            /#151515/ { gsub(/#151515/, border) }
            /#000000/ { gsub(/#000000/, border) }
            { print }
        ' "$base_svg" >"$k_dir/$k_theme.svg"
    else
        cat >"$k_dir/$k_theme.svg" <<EOF
<svg width="96" height="96" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="anto426Button" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="$surface"/>
      <stop offset="1" stop-color="$background"/>
    </linearGradient>
  </defs>
  <rect id="common" x="4" y="4" width="24" height="24" rx="6" fill="$surface" stroke="$border"/>
  <rect id="button" x="36" y="4" width="24" height="24" rx="6" fill="url(#anto426Button)" stroke="$border"/>
  <rect id="lineedit" x="68" y="4" width="24" height="24" rx="5" fill="$background" stroke="$border"/>
  <rect id="focus" x="4" y="36" width="24" height="24" rx="6" fill="none" stroke="$accent" stroke-width="2"/>
  <rect id="tab" x="36" y="36" width="24" height="24" rx="5" fill="$select" stroke="$accent"/>
  <rect id="dock" x="68" y="36" width="24" height="24" rx="4" fill="$surface" stroke="$border"/>
  <circle id="radio" cx="16" cy="80" r="8" fill="$background" stroke="$accent" stroke-width="2"/>
  <rect id="checkbox" x="36" y="68" width="18" height="18" rx="4" fill="$background" stroke="$accent" stroke-width="2"/>
  <path id="arrow" d="M72 72 L84 80 L72 88 Z" fill="$foreground"/>
  <path id="arrow-down" d="M8 8 L20 8 L14 16 Z" fill="$foreground"/>
  <path id="spin" d="M44 70 L52 78 L44 86 Z" fill="$foreground"/>
</svg>
EOF
    fi

    if ((use_base)); then
        awk \
            -v background="$background" \
            -v surface="$surface" \
            -v select="$select" \
            -v accent="$accent" \
            -v border="$border" \
            -v foreground="${foreground}c8" \
            -v muted="${muted}99" \
            -v tooltip="$foreground" \
            -v highlight_text="$background" '
            /^author=/ { print "author=anto426"; next }
            /^comment=/ { print "comment=Dynamic anto426 palette generated from the active wallpaper"; next }
            /^window.color=/ { print "window.color=" surface; next }
            /^base.color=/ { print "base.color=" background; next }
            /^alt.base.color=/ { print "alt.base.color=" surface; next }
            /^button.color=/ { print "button.color=" surface; next }
            /^light.color=/ { print "light.color=" select; next }
            /^mid.light.color=/ { print "mid.light.color=" border; next }
            /^dark.color=/ { print "dark.color=" background; next }
            /^mid.color=/ { print "mid.color=" border; next }
            /^highlight.color=/ { print "highlight.color=" accent; next }
            /^inactive.highlight.color=/ { print "inactive.highlight.color=" select; next }
            /^text.color=/ { print "text.color=" foreground; next }
            /^window.text.color=/ { print "window.text.color=" foreground; next }
            /^button.text.color=/ { print "button.text.color=" foreground; next }
            /^disabled.text.color=/ { print "disabled.text.color=" muted; next }
            /^tooltip.text.color=/ { print "tooltip.text.color=" tooltip; next }
            /^highlight.text.color=/ { print "highlight.text.color=" highlight_text; next }
            /^link.color=/ { print "link.color=" accent; next }
            /^link.visited.color=/ { print "link.visited.color=" select; next }
            { print }
        ' "$base_config" >"$k_dir/$k_theme.kvconfig"
    else
        cat >"$k_dir/$k_theme.kvconfig" <<EOF
[%General]
author=anto426
comment=Dynamic anto426 palette generated from the active wallpaper
x11drag=menubar_and_primary_toolbar
alt_mnemonic=true
left_tabs=true
attach_active_tab=true
mirror_doc_tabs=true
composite=true
menu_shadow_depth=5
tooltip_shadow_depth=6
scroll_width=9
scroll_arrows=false
slider_width=6
slider_handle_width=18
check_size=14
menubar_mouse_tracking=true
toolbutton_style=1
translucent_windows=false
blurring=false
popup_blurring=false
merge_menubar_with_toolbar=true
small_icon_size=16
large_icon_size=32
button_icon_size=16
toolbar_icon_size=22
layout_spacing=6
layout_margin=9
scrollbar_in_view=true
transient_scrollbar=true
submenu_overlap=3

[GeneralColors]
window.color=$surface
base.color=$background
alt.base.color=$surface
button.color=$surface
light.color=$select
mid.light.color=$border
dark.color=$background
mid.color=$border
highlight.color=$accent
inactive.highlight.color=$select
text.color=${foreground}c8
window.text.color=${foreground}c8
button.text.color=${foreground}c8
disabled.text.color=${muted}99
tooltip.text.color=$foreground
highlight.text.color=$background
link.color=$accent
link.visited.color=$select
progress.indicator.text.color=$background

[PanelButtonCommand]
frame=true
frame.element=button
frame.top=3
frame.bottom=3
frame.left=3
frame.right=3
interior=true
interior.element=button
indicator.size=9
indicator.element=arrow
text.normal.color=${foreground}c8
text.focus.color=$foreground
text.press.color=$foreground
text.toggle.color=$foreground
text.shadow=0
text.margin=1
text.iconspacing=4
min_width=+0.3font
min_height=+0.3font
frame.expansion=6

[PanelButtonTool]
inherits=PanelButtonCommand

[Dock]
inherits=PanelButtonCommand
interior.element=dock
frame.element=dock

[RadioButton]
inherits=PanelButtonCommand
frame=false
interior.element=radio

[CheckBox]
inherits=PanelButtonCommand
frame=false
interior.element=checkbox

[Focus]
inherits=PanelButtonCommand
frame=true
frame.element=focus
interior=false

[GenericFrame]
inherits=PanelButtonCommand
frame=true
interior=false
frame.element=common

[LineEdit]
inherits=PanelButtonCommand
frame.element=lineedit
interior.element=lineedit

[DropDownButton]
inherits=PanelButtonCommand
indicator.element=arrow-down

[IndicatorArrow]
indicator.element=arrow
indicator.size=9

[IndicatorSpinBox]
inherits=PanelButtonCommand
indicator.element=spin
indicator.size=10

[Tab]
inherits=PanelButtonCommand
interior.element=tab
frame.element=tab
text.margin.left=8
text.margin.right=8

[Hacks]
respect_darkness=true
force_size_grip=true
iconless_pushbutton=true
normal_default_pushbutton=true
single_top_toolbar=true
EOF
    fi

    cat >"$kvantum_config_file" <<EOF
[General]
theme=$k_theme
EOF

    log "Kvantum theme attivo: $k_theme"
}

write_app_theme() {
    write_gtk_theme
    write_qt_theme
    write_kvantum_theme
    gtk_reload_theme
    restart_gtk_portals
}
