#!/usr/bin/env bash

write_sddm_theme() {
    make_cover_image "$current_wallpaper_path" "$canvas_size" "$tmp_dir/sddm-background.jpg" jpg 94
    install_file "$tmp_dir/sddm-background.jpg" "$sddm_background" "SDDM background" || true

    [[ -f "$sddm_theme" ]] || return 0

    awk \
        -v bg="$background" \
        -v fg="$foreground" \
        -v muted="$muted" \
        -v accent="$accent" \
        -v width="$canvas_width" \
        -v height="$canvas_height" '
        /^Background=/ { print "Background=\"Backgrounds/current_wallpaper.jpg\""; next }
        /^ScreenWidth=/ { print "ScreenWidth=\"" width "\""; next }
        /^ScreenHeight=/ { print "ScreenHeight=\"" height "\""; next }
        /^MainColor=/ { print "MainColor=\"" fg "\""; next }
        /^AccentColor=/ { print "AccentColor=\"" accent "\""; next }
        /^BackgroundColor=/ { print "BackgroundColor=\"" bg "\""; next }
        /^OverrideLoginButtonTextColor=/ { print "OverrideLoginButtonTextColor=\"" bg "\""; next }
        { print }
    ' "$sddm_theme" >"$tmp_dir/sddm-theme.conf"
    install_file "$tmp_dir/sddm-theme.conf" "$sddm_theme" "SDDM theme" || true
}

write_grub_theme() {
    make_grub_background "$current_wallpaper_path" "$canvas_size" "$tmp_dir/grub-background.jpg"
    install_file "$tmp_dir/grub-background.jpg" "$grub_background" "GRUB background" || true
    make_grub_select_pixmaps "$tmp_dir"
    install_optional_file "$tmp_dir/select_c.png" "$grub_select_c" "GRUB selection center" || true
    install_optional_file "$tmp_dir/select_e.png" "$grub_select_e" "GRUB selection east" || true
    install_optional_file "$tmp_dir/select_w.png" "$grub_select_w" "GRUB selection west" || true

    cat >"$tmp_dir/grub-theme.txt" <<EOF
# GRUB2 gfxmenu theme generated by wallpaper_effects.sh
# Coherent with the active anto426 wallpaper palette.

title-text: ""
desktop-image: "background.jpg"
desktop-color: "$background"
terminal-font: "Terminus Regular 18"
terminal-box: "terminal_box_*.png"
terminal-width: "100%"
terminal-height: "100%"
terminal-border: "0"

+ label {
  top = 15%
  left = 0
  width = 100%
  align = "center"
  text = "anto426"
  color = "$foreground"
  font = "Unifont Regular 32"
}

+ label {
  top = 20%
  left = 0
  width = 100%
  align = "center"
  text = "Select a system"
  color = "$muted"
  font = "Unifont Regular 16"
}

+ boot_menu {
  left = 21%
  top = 30%
  width = 58%
  height = 38%
  item_font = "Unifont Regular 24"
  item_color = "$muted"
  selected_item_color = "$foreground"
  icon_width = 44
  icon_height = 44
  item_icon_space = 22
  item_height = 58
  item_padding = 12
  item_spacing = 10
  selected_item_pixmap_style = "select_*.png"
}

+ label {
  top = 84%
  left = 24%
  width = 52%
  align = "center"
  id = "__timeout__"
  text = "Booting in %d seconds"
  color = "$accent"
  font = "Unifont Regular 20"
}
EOF
    install_file "$tmp_dir/grub-theme.txt" "$grub_theme" "GRUB theme" || true
}

write_boot_theme() {
    write_grub_theme
    write_sddm_theme
}
