#!/usr/bin/env bash
# Palette generation from wallpaper RGB samples.
# Outputs semantic tokens consumed by Hyprland, Rofi, GTK, Ghostty, GRUB, SDDM.

generate_palette_from_samples() {
    local r="$1"
    local g="$2"
    local b="$3"
    local ar="$4"
    local ag="$5"
    local ab="$6"

    read -r background surface select accent border foreground muted red orange yellow green pink purple gray base base_alt titlebar titlebar_backdrop popover selected_fg < <(
        awk -v r="$r" -v g="$g" -v b="$b" -v ar="$ar" -v ag="$ag" -v ab="$ab" '
            function clamp(v) { return v < 0 ? 0 : (v > 255 ? 255 : int(v + 0.5)) }
            function hex(rr, gg, bb) { return sprintf("#%02x%02x%02x", clamp(rr), clamp(gg), clamp(bb)) }
            function mix(a, b, ratio) { return a * (1 - ratio) + b * ratio }
            function brightness(rr, gg, bb) { return (299 * rr + 587 * gg + 114 * bb) / 1000 }
            BEGIN {
                bg_r = clamp(r * 0.36 + ar * 0.08)
                bg_g = clamp(g * 0.36 + ag * 0.08)
                bg_b = clamp(b * 0.36 + ab * 0.08)

                surface_r = clamp(r * 0.52 + ar * 0.22 + 255 * 0.12)
                surface_g = clamp(g * 0.52 + ag * 0.22 + 255 * 0.12)
                surface_b = clamp(b * 0.52 + ab * 0.22 + 255 * 0.12)

                select_r = clamp(r * 0.45 + ar * 0.35 + 255 * 0.20)
                select_g = clamp(g * 0.45 + ag * 0.35 + 255 * 0.20)
                select_b = clamp(b * 0.45 + ab * 0.35 + 255 * 0.20)

                accent_r = clamp(ar * 0.70 + 255 * 0.30)
                accent_g = clamp(ag * 0.70 + 255 * 0.30)
                accent_b = clamp(ab * 0.70 + 255 * 0.30)

                border_r = clamp(r * 0.45 + ar * 0.25 + 255 * 0.24)
                border_g = clamp(g * 0.45 + ag * 0.25 + 255 * 0.24)
                border_b = clamp(b * 0.45 + ab * 0.25 + 255 * 0.24)

                bg_brightness = brightness(bg_r, bg_g, bg_b)
                fg = bg_brightness > 155 ? "#11111b" : "#f6f7fb"
                muted = bg_brightness > 155 ? "#343746" : "#b9c4d2"

                background = hex(bg_r, bg_g, bg_b)
                surface = hex(surface_r, surface_g, surface_b)
                select = hex(select_r, select_g, select_b)
                accent = hex(accent_r, accent_g, accent_b)
                border = hex(border_r, border_g, border_b)

                base = hex(mix(bg_r, surface_r, 0.22), mix(bg_g, surface_g, 0.22), mix(bg_b, surface_b, 0.22))
                base_alt = hex(mix(bg_r, surface_r, 0.58), mix(bg_g, surface_g, 0.58), mix(bg_b, surface_b, 0.58))
                titlebar = surface
                titlebar_backdrop = hex(mix(bg_r, surface_r, 0.78), mix(bg_g, surface_g, 0.78), mix(bg_b, surface_b, 0.78))
                popover = hex(mix(bg_r, surface_r, 0.78), mix(bg_g, surface_g, 0.78), mix(bg_b, surface_b, 0.78))
                selected_fg = brightness(accent_r, accent_g, accent_b) > 155 ? "#11111b" : "#f6f7fb"

                red = hex(ar * 0.15 + 243 * 0.85, ag * 0.15 + 139 * 0.85, ab * 0.15 + 168 * 0.85)
                orange = hex(ar * 0.12 + 250 * 0.88, ag * 0.12 + 179 * 0.88, ab * 0.10 + 135 * 0.90)
                yellow = hex(ar * 0.08 + 249 * 0.92, ag * 0.08 + 226 * 0.92, ab * 0.05 + 175 * 0.95)
                green = hex(ar * 0.12 + 166 * 0.88, ag * 0.15 + 227 * 0.85, ab * 0.12 + 161 * 0.88)
                pink = hex(ar * 0.15 + 245 * 0.85, ag * 0.15 + 194 * 0.85, ab * 0.15 + 231 * 0.85)
                purple = hex(ar * 0.15 + 203 * 0.85, ag * 0.12 + 166 * 0.88, ab * 0.15 + 247 * 0.85)
                gray = hex(r * 0.20 + 108 * 0.80, g * 0.20 + 112 * 0.80, b * 0.20 + 134 * 0.80)

                print background, surface, select, accent, border, fg, muted, red, orange, yellow, green, pink, purple, gray, base, base_alt, titlebar, titlebar_backdrop, popover, selected_fg
            }
        '
    )

    panel_bg="$(hex_to_rofi_rgba "$background" 62)"
    panel_bg_hover="$(hex_to_rofi_rgba "$background" 78)"
    overlay_bg="$(hex_to_rofi_rgba "$background" 28)"
    item_bg="$(hex_to_rofi_rgba "$surface" 18)"
    item_bg_hover="$(hex_to_rofi_rgba "$select" 30)"
    item_bg_active="$(hex_to_rofi_rgba "$select" 42)"
    accent_soft="$(hex_to_rofi_rgba "$accent" 22)"
    accent_strong="$(hex_to_rofi_rgba "$accent" 42)"
    border_soft="$(hex_to_rofi_rgba "$border" 16)"
    border_medium="$(hex_to_rofi_rgba "$border" 34)"
    shadow_soft="$(hex_to_rofi_rgba "$background" 18)"
    shadow_medium="$(hex_to_rofi_rgba "$background" 30)"

    background_alpha="$panel_bg"
    surface_alpha="$item_bg"
    select_alpha="$item_bg_active"
    accent_alpha="$accent_strong"
    border_alpha="$border_medium"
}

write_palette_map() {
    local map_file="${1:-$state_dir/palette.map}"
    [[ -n "${state_dir:-}" ]] || return 0

    mkdir -p "$(dirname "$map_file")"
    cat >"$map_file" <<EOF
# Generated by wallpaper_effects.sh — palette routing map
# wallpaper=$current_wallpaper_path

[core]
background=$background
surface=$surface
base=$base
base_alt=$base_alt
foreground=$foreground
muted=$muted
accent=$accent
select=$select
border=$border
selected_fg=$selected_fg

[semantic]
titlebar=$titlebar
titlebar_backdrop=$titlebar_backdrop
popover=$popover
red=$red
orange=$orange
yellow=$yellow
green=$green
pink=$pink
purple=$purple
gray=$gray

[targets.session]
hypr=theme.generated.conf
colors=colors.{css,rasi,sh}
ghostty=dynamic.conf + themes/anto426
vscode=$vscode_theme_file
htop=$HOME/.config/htop/htoprc

[targets.apps]
gtk3=$gtk3_dir/gtk.css
gtk4=$gtk4_dir/gtk.css
qt5ct=$qt5ct_dir/colors/anto426.conf
qt6ct=$qt6ct_dir/colors/anto426.conf
kvantum=$kvantum_theme_dir

[targets.boot]
grub=$grub_theme_dir
sddm=$sddm_background

[htop.tokens]
color_scheme=0
source=terminal-ansi-palette
EOF
}
