#!/usr/bin/env bash

write_color_files() {
    cat >"$colors_dir/colors.css" <<EOF
@define-color background $background;
@define-color surface    $surface;
@define-color foreground $foreground;
@define-color muted      $muted;
@define-color select     $select;
@define-color accent     $accent;
@define-color border     $border;

@define-color background-alpha $(hex_to_css_rgba "$background" 0.60);
@define-color surface-alpha    $(hex_to_css_rgba "$surface" 0.78);
@define-color select-alpha     $(hex_to_css_rgba "$select" 0.76);
@define-color accent-alpha     $(hex_to_css_rgba "$accent" 0.84);
@define-color border-alpha     $(hex_to_css_rgba "$border" 0.55);

@define-color pink       $pink;
@define-color purple     $purple;
@define-color red        $red;
@define-color orange     $orange;
@define-color yellow     $yellow;
@define-color green      $green;
@define-color blue       @accent;
@define-color gray       $gray;
EOF

    cat >"$colors_dir/colors.rasi" <<EOF
* {
    background: $background;
    surface: $surface;
    background-alpha: $background_alpha;
    surface-alpha: $surface_alpha;
    foreground: $foreground;
    muted: $muted;
    select: $select;
    select-alpha: $select_alpha;

    accent: $accent;
    accent-alpha: $accent_alpha;
    border: $border;
    border-alpha: $border_alpha;
    pink: $pink;
    purple: $purple;
    red: $red;
    orange: $orange;
    yellow: $yellow;
    green: $green;
    blue: @accent;
    gray: $gray;

    active-background: @select;
    urgent-background: @red;
    urgent-foreground: @background;
    selected-background: @accent;
    selected-urgent-background: @urgent-background;
    selected-active-background: @active-background;
    bordercolor: @border;
}
EOF

    cat >"$colors_dir/colors.sh" <<EOF
# Generated by wallpaper_effects.sh
export ANTO426_BACKGROUND="$background"
export ANTO426_SURFACE="$surface"
export ANTO426_FOREGROUND="$foreground"
export ANTO426_MUTED="$muted"
export ANTO426_SELECT="$select"
export ANTO426_ACCENT="$accent"
export ANTO426_BORDER="$border"
export ANTO426_WALLPAPER="$current_wallpaper_path"
EOF
}

write_hypr_theme() {
    cat >"$hypr_theme_file" <<EOF
# Generated by wallpaper_effects.sh
\$anto426_wallpaper = $destination_wallpaper_dir/normal.png
\$anto426_background = $(hypr_rgb "$background")
\$anto426_surface = $(hypr_rgb "$surface")
\$anto426_foreground = $(hypr_rgb "$foreground")
\$anto426_muted = $(hypr_rgb "$muted")
\$anto426_accent = $(hypr_rgb "$accent")
\$anto426_border = $(hypr_rgb "$border")
\$anto426_muted_hex = $muted

\$anto426_active_border = $(hypr_rgba "$accent" ee)
\$anto426_inactive_border = $(hypr_rgba "$background" aa)
\$anto426_shadow = rgba(000000aa)
\$anto426_foreground_strong = $(hypr_rgba "$foreground" e6)
\$anto426_accent_strong = $(hypr_rgba "$accent" f2)
\$anto426_accent_soft = $(hypr_rgba "$accent" cc)
\$anto426_surface_soft = $(hypr_rgba "$surface" 59)
\$anto426_border_soft = $(hypr_rgba "$border" 66)
EOF
}

write_terminal_theme() {
    # 1. Write the theme file with the current wallpaper colors
    mkdir -p "$ghostty_theme_dir"
    cat >"$ghostty_theme_dir/anto426" <<EOF
palette = 0=$background
palette = 1=$red
palette = 2=$green
palette = 3=$yellow
palette = 4=$accent
palette = 5=$pink
palette = 6=$muted
palette = 7=$foreground
palette = 8=$gray
palette = 9=$red
palette = 10=$green
palette = 11=$yellow
palette = 12=$accent
palette = 13=$purple
palette = 14=$muted
palette = 15=#ffffff
background = ${background#\#}
foreground = ${foreground#\#}
cursor-color = ${accent#\#}
cursor-text = ${background#\#}
selection-background = ${select#\#}
selection-foreground = ${foreground#\#}
EOF

    # 2. Rewrite the Ghostty main config with actual content (not just 'touch').
    # 'touch' only triggers IN_ATTRIB; Ghostty's inotify watcher needs IN_CLOSE_WRITE.
    # We read the static (non-color) settings from the dotfiles reference config,
    # then write a new config that references our theme via 'theme = anto426'.
    local ghostty_config="$HOME/.config/ghostty/config"
    local ghostty_ref_config

    # Find the dotfiles reference config to get the user's static settings
    for ghostty_ref_config in \
        "$HOME/dotfiles/.config/ghostty/config" \
        "$HOME/Git/arch/dotfiles/.config/ghostty/config"; do
        [[ -f "$ghostty_ref_config" ]] && break
    done

    if [[ -f "$ghostty_ref_config" ]]; then
        # Use the dotfiles config as the base for static settings, strip any old color block
        {
            grep -v '^#.*Generated\|^palette\s*=\|^background\s*=\|^foreground\s*=\|^cursor-color\s*=\|^cursor-text\s*=\|^selection-background\s*=\|^selection-foreground\s*=' \
                "$ghostty_ref_config" \
                | grep -v '^$' | head -20
            printf '\n# Generated: %s\n' "$(date '+%Y-%m-%dT%H:%M:%S')"
        } >"$ghostty_config"
    else
        # Fallback: write a minimal config
        cat >"$ghostty_config" <<EOF
font-family = JetBrainsMono Nerd Font
font-size = 13
theme = anto426
background-opacity = 0.82
background-blur = true
keybind = ctrl+shift+v=ignore
keybind = performable:ctrl+v=paste_from_clipboard
keybind = ctrl+shift+c=ignore
keybind = performable:ctrl+c=copy_to_clipboard
# Generated: $(date '+%Y-%m-%dT%H:%M:%S')
EOF
    fi

    log "Ghostty tema aggiornato: bg=${background} accent=${accent}"
}

write_session_theme() {
    write_color_files
    write_hypr_theme
    write_terminal_theme
}
