#!/usr/bin/env bash

write_color_files() {
    cat >"$colors_dir/colors.css" <<EOF
@define-color background $background;
@define-color surface    $surface;
@define-color base       $base;
@define-color base-alt   $base_alt;
@define-color titlebar   $titlebar;
@define-color titlebar-backdrop $titlebar_backdrop;
@define-color popover    $popover;
@define-color foreground $foreground;
@define-color muted      $muted;
@define-color select     $select;
@define-color accent     $accent;
@define-color selected-fg $selected_fg;
@define-color border     $border;

@define-color background-alpha $(hex_to_css_rgba "$background" 0.60);
@define-color surface-alpha    $(hex_to_css_rgba "$surface" 0.78);
@define-color select-alpha     $(hex_to_css_rgba "$select" 0.76);
@define-color accent-alpha     $(hex_to_css_rgba "$accent" 0.84);
@define-color border-alpha     $(hex_to_css_rgba "$border" 0.55);

@define-color pink       $pink;
@define-color purple     $purple;
@define-color red        $red;
@define-color orange     $orange;
@define-color yellow     $yellow;
@define-color green      $green;
@define-color blue       @accent;
@define-color gray       $gray;
EOF

    cat >"$colors_dir/colors.rasi" <<EOF
* {
    background: $background;
    surface: $surface;
    base: $base;
    base-alt: $base_alt;
    titlebar: $titlebar;
    titlebar-backdrop: $titlebar_backdrop;
    popover: $popover;
    background-alpha: $background_alpha;
    surface-alpha: $surface_alpha;
    foreground: $foreground;
    muted: $muted;
    select: $select;
    select-alpha: $select_alpha;

    accent: $accent;
    selected-fg: $selected_fg;
    accent-alpha: $accent_alpha;
    border: $border;
    border-alpha: $border_alpha;
    pink: $pink;
    purple: $purple;
    red: $red;
    orange: $orange;
    yellow: $yellow;
    green: $green;
    blue: @accent;
    gray: $gray;

    active-background: @select;
    urgent-background: @red;
    urgent-foreground: @background;
    selected-background: @accent;
    selected-urgent-background: @urgent-background;
    selected-active-background: @active-background;
    bordercolor: @border;
}
EOF

    cat >"$colors_dir/colors.sh" <<EOF
# Generated by wallpaper_effects.sh
export ANTO426_BACKGROUND="$background"
export ANTO426_SURFACE="$surface"
export ANTO426_BASE="$base"
export ANTO426_BASE_ALT="$base_alt"
export ANTO426_TITLEBAR="$titlebar"
export ANTO426_TITLEBAR_BACKDROP="$titlebar_backdrop"
export ANTO426_POPOVER="$popover"
export ANTO426_FOREGROUND="$foreground"
export ANTO426_MUTED="$muted"
export ANTO426_SELECT="$select"
export ANTO426_ACCENT="$accent"
export ANTO426_SELECTED_FG="$selected_fg"
export ANTO426_BORDER="$border"
export ANTO426_WALLPAPER="$current_wallpaper_path"
EOF
}

write_hypr_theme() {
    cat >"$hypr_theme_file" <<EOF
# Generated by wallpaper_effects.sh
\$anto426_wallpaper = $destination_wallpaper_dir/normal.png
\$anto426_background = $(hypr_rgb "$background")
\$anto426_surface = $(hypr_rgb "$surface")
\$anto426_foreground = $(hypr_rgb "$foreground")
\$anto426_muted = $(hypr_rgb "$muted")
\$anto426_accent = $(hypr_rgb "$accent")
\$anto426_border = $(hypr_rgb "$border")
\$anto426_muted_hex = $muted

\$anto426_active_border = $(hypr_rgba "$accent" ee)
\$anto426_inactive_border = $(hypr_rgba "$background" aa)
\$anto426_shadow = rgba(00000055)
\$anto426_background_panel = $(hypr_rgba "$background" cc)
\$anto426_background_soft = $(hypr_rgba "$background" 99)
\$anto426_surface_panel = $(hypr_rgba "$surface" c7)
\$anto426_border_panel = $(hypr_rgba "$border" 8c)
\$anto426_foreground_strong = $(hypr_rgba "$foreground" e6)
\$anto426_accent_strong = $(hypr_rgba "$accent" f2)
\$anto426_accent_soft = $(hypr_rgba "$accent" cc)
\$anto426_surface_soft = $(hypr_rgba "$surface" 59)
\$anto426_border_soft = $(hypr_rgba "$border" 66)
EOF
}

write_terminal_theme() {
    # Write the Ghostty theme file with the dynamic wallpaper colors
    mkdir -p "$ghostty_theme_dir"
    cat >"$ghostty_theme_dir/anto426" <<EOF
palette = 0=$background
palette = 1=$red
palette = 2=$green
palette = 3=$yellow
palette = 4=$accent
palette = 5=$pink
palette = 6=$muted
palette = 7=$foreground
palette = 8=$gray
palette = 9=$red
palette = 10=$green
palette = 11=$yellow
palette = 12=$accent
palette = 13=$purple
palette = 14=$muted
palette = 15=#ffffff
background = ${background#\#}
foreground = ${foreground#\#}
cursor-color = ${accent#\#}
cursor-text = ${background#\#}
selection-background = ${select#\#}
selection-foreground = ${foreground#\#}
EOF

    # Write colors to the dynamic include file (NOT the stow-managed config).
    # The main config has: config-file = ~/.config/ghostty/dynamic.conf
    # Ghostty watches all loaded config files, so writing here triggers hot-reload.
    cat >"$HOME/.config/ghostty/dynamic.conf" <<EOF
# Generated by wallpaper_effects.sh at $(date '+%Y-%m-%dT%H:%M:%S')
palette = 0=${background#\#}
palette = 1=${red#\#}
palette = 2=${green#\#}
palette = 3=${yellow#\#}
palette = 4=${accent#\#}
palette = 5=${pink#\#}
palette = 6=${muted#\#}
palette = 7=${foreground#\#}
palette = 8=${gray#\#}
palette = 9=${red#\#}
palette = 10=${green#\#}
palette = 11=${yellow#\#}
palette = 12=${accent#\#}
palette = 13=${purple#\#}
palette = 14=${muted#\#}
palette = 15=ffffff
background = ${background#\#}
foreground = ${foreground#\#}
cursor-color = ${accent#\#}
cursor-text = ${background#\#}
selection-background = ${select#\#}
selection-foreground = ${foreground#\#}
EOF
}

write_htop_theme() {
    local target="$htop_config_dir/htoprc"
    local htop_version
    local tmp

    mkdir -p "$htop_config_dir"
    htop_version="$(htop --version 2>/dev/null | awk 'NR == 1 { print $2; exit }')"
    htop_version="${htop_version:-3.5.1}"

    if [[ -f "$target" ]]; then
        tmp="$(mktemp)"
        awk '
            BEGIN {
                seen_color = 0
                seen_base = 0
                seen_megabytes = 0
            }
            /^color_scheme=/ {
                print "color_scheme=0"
                seen_color = 1
                next
            }
            /^highlight_base_name=/ {
                print "highlight_base_name=1"
                seen_base = 1
                next
            }
            /^highlight_megabytes=/ {
                print "highlight_megabytes=1"
                seen_megabytes = 1
                next
            }
            { print }
            END {
                if (!seen_color) print "color_scheme=0"
                if (!seen_base) print "highlight_base_name=1"
                if (!seen_megabytes) print "highlight_megabytes=1"
            }
        ' "$target" >"$tmp"
        mv "$tmp" "$target"
        log "htop palette aggiornata: $target"
        return 0
    fi

    cat >"$target" <<EOF
# Generated by wallpaper_effects.sh
# htop reads ANSI colors from the terminal; color_scheme=0 lets Ghostty's
# dynamic wallpaper palette drive the UI.
htop_version=$htop_version
config_reader_min_version=3
fields=0 48 17 18 38 39 130 2 46 47 49 1
hide_kernel_threads=1
hide_userland_threads=0
hide_running_in_container=0
shadow_other_users=1
show_thread_names=0
show_program_path=1
highlight_base_name=1
highlight_deleted_exe=1
shadow_distribution_path_prefix=0
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
header_margin=1
screen_tabs=1
detailed_cpu_time=0
cpu_count_from_one=1
show_cpu_usage=1
show_cpu_frequency=1
show_cpu_temperature=1
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
hide_function_bar=0
header_layout=two_50_50
column_meters_0=LeftCPUs Memory Swap
column_meter_modes_0=1 1 1
column_meters_1=RightCPUs Tasks LoadAverage Uptime
column_meter_modes_1=1 2 2 2
tree_view=0
sort_key=46
tree_sort_key=0
sort_direction=-1
tree_sort_direction=1
tree_view_always_by_pid=0
all_branches_collapsed=0
screen:Main=PID USER PRIORITY NICE M_VIRT M_RESIDENT M_PRIV STATE PERCENT_CPU PERCENT_MEM TIME Command
.sort_key=PERCENT_CPU
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
screen:I/O=PID USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE PERCENT_SWAP_DELAY PERCENT_IO_DELAY Command
.sort_key=IO_RATE
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
EOF

    log "htop palette creata: $target"
}

write_session_theme() {
    write_color_files
    write_hypr_theme
    write_terminal_theme
    write_htop_theme
    write_palette_map "$state_dir/palette.map"
}
