# Anto426 btop config
color_theme = "anto426"
theme_background = false
truecolor = true
rounded_corners = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_colors = true
proc_gradient = true
proc_cpu_graphs = true
check_temp = true
show_coretemp = true
show_cpu_freq = true
show_uptime = true
mem_graphs = true
show_disks = true
net_auto = true
