#!/usr/bin/env python3
"""Install application palette artifacts without rewriting user documents."""
from pathlib import Path
import argparse
import colorsys
import configparser
import json
import os
import re
import tempfile


def atomic_write(path, text):
    path = Path(path)
    content = text.encode() if isinstance(text, str) else text
    if path.is_file() and path.read_bytes() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o600
    descriptor, temporary = tempfile.mkstemp(prefix=".anto-theme-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return True


def update_ini(path, updates):
    """Patch owned INI keys while retaining comments, fonts and other preferences."""
    text = path.read_text() if path.is_file() else ""
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    parser.read_string(text)
    lines = text.splitlines(keepends=True)
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"
    sections, positions = {}, {}
    section = None
    for index, line in enumerate(lines):
        match = re.match(r"\s*\[([^]]+)\]", line)
        if match:
            section = match[1]
            sections[section] = index
        elif section and not line.lstrip().startswith(("#", ";")):
            match = re.match(r"\s*([^=]+?)\s*=", line)
            if match:
                positions[section, match[1].strip()] = index
    insertions = {}
    appended = []
    for section, entries in updates.items():
        missing = []
        for key, value in entries.items():
            if value is None:
                if (section, key) in positions:
                    lines[positions[section, key]] = ""
                continue
            if (section, key) in positions:
                index = positions[section, key]
                lines[index] = lines[index].split("=", 1)[0] + "=" + value + "\n"
            else:
                missing.append(key + "=" + value + "\n")
        if not missing:
            continue
        if section in sections:
            end = next((i for i in sorted(sections.values()) if i > sections[section]), len(lines))
            insertions.setdefault(end, []).extend(missing)
        else:
            appended.extend(["\n[" + section + "]\n", *missing])
    for index in sorted(insertions, reverse=True):
        lines[index:index] = insertions[index]
    result = "".join(lines).rstrip() + "\n" + "".join(appended)
    parser.read_string(result)
    return atomic_write(path, result)


def install_gtk(artifact):
    home = Path.home()
    config = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    data = Path(os.environ.get("XDG_DATA_HOME", home / ".local/share"))
    roots = (home / ".themes/anto426", data / "themes/anto426")
    for target in roots:
        for source in artifact.rglob("*"):
            if source.is_file():
                atomic_write(target / source.relative_to(artifact), source.read_bytes())
    for version in ("3.0", "4.0"):
        directory = config / ("gtk-" + version)
        css = directory / "gtk.css"
        text = css.read_text() if css.is_file() else ""
        if text.startswith("/* Generated by wallpaper_effects.sh"):
            start = text.find("scale > trough > slider:active {")
            end = text.find("\n}", start) if start >= 0 else -1
            if end < 0:
                raise ValueError("Unrecognized legacy GTK stylesheet; preserving it")
            text = text[end + 2:]
        text = re.sub(r"/\* Anto426 palette begin \*/.*?/\* Anto426 palette end \*/\n?", "", text, flags=re.S)
        include = roots[1] / ("gtk-" + version) / "palette.css"
        block = '/* Anto426 palette begin */\n@import url(' + json.dumps(str(include)) + ');\n/* Anto426 palette end */\n'
        atomic_write(css, block + text.lstrip("\n"))
        update_ini(directory / "settings.ini", {"Settings": {"gtk-theme-name": "anto426", "gtk-application-prefer-dark-theme": "true" if version == "3.0" else None}})
    print("GTK3/GTK4 and libadwaita palette installed")


def install_qt(artifact):
    home = Path.home()
    config = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    for version in (5, 6):
        directory = config / f"qt{version}ct"
        palette = directory / "colors/anto426.conf"
        stylesheet = directory / "anto426.qss"
        atomic_write(palette, (artifact / f"qt{version}.conf").read_bytes())
        assets = directory / 'anto426-assets'
        if (artifact / 'assets').is_dir():
            for source in (artifact / 'assets').iterdir():
                atomic_write(assets / source.name, source.read_bytes())
        qss = (artifact / f"qt{version}.qss").read_text().replace('@ANTO_QT_ASSETS@', str(assets).replace('\\', '\\\\').replace(chr(34), '\\' + chr(34)))
        atomic_write(stylesheet, qss)
        settings = directory / f"qt{version}ct.conf"
        current = configparser.ConfigParser(interpolation=None)
        current.read(settings)
        existing = current.get("Interface", "stylesheets", fallback="")
        stylesheets = existing if str(stylesheet) in [item.strip() for item in existing.split(",")] else ", ".join(filter(None, (existing, str(stylesheet))))
        update_ini(settings, {"Appearance": {"color_scheme_path": str(palette), "custom_palette": "true", "style": "kvantum"}, "Interface": {"stylesheets": stylesheets}})
    theme = config / "Kvantum/anto426"
    for name in ("anto426.svg", "anto426.kvconfig"):
        atomic_write(theme / name, (artifact / name).read_bytes())
    update_ini(config / "Kvantum/kvantum.kvconfig", {"General": {"theme": "anto426"}})
    quick = config / 'anto426-local/theme/qtquickcontrols2.conf'
    atomic_write(quick, (artifact / 'qtquickcontrols2.conf').read_bytes())
    data = Path(os.environ.get('XDG_DATA_HOME', home / '.local/share'))
    qml = data / 'anto-desktop/qml'
    if (artifact / 'qml').is_dir():
        for source in (artifact / 'qml').rglob('*'):
            if source.is_file():
                atomic_write(qml / source.relative_to(artifact / 'qml'), source.read_bytes())
    environment = config / "environment.d/99-anto426-qt.conf"
    text = environment.read_text() if environment.is_file() else ""
    for key, value in (("QT_QPA_PLATFORMTHEME", "qt5ct"), ('QT_STYLE_OVERRIDE', ''), ('QT_QUICK_CONTROLS_CONF', str(quick)),
                       ('QT_QUICK_CONTROLS_STYLE_PATH', str(qml)),
                       ('QML_IMPORT_PATH', str(qml) + '${QML_IMPORT_PATH:+:$QML_IMPORT_PATH}'),
                       ('QML2_IMPORT_PATH', str(qml) + '${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}')):
        line = key + "=" + value
        if re.search(r"^" + key + "=", text, flags=re.M):
            text = re.sub(r"^" + key + "=.*$", line, text, flags=re.M)
        else:
            text = text.rstrip() + "\n" + line + "\n"
    atomic_write(environment, text.lstrip("\n"))
    print("Qt5/Qt6 and Kvantum palette installed")


def jsonc_tokens(text):
    """Lex JSONC, preserving spans so unrelated preferences keep their comments."""
    index = 0
    tokens = []
    while index < len(text):
        char = text[index]
        if char.isspace():
            index += 1
            continue
        if text.startswith("//", index):
            end = text.find("\n", index)
            index = len(text) if end < 0 else end
            continue
        if text.startswith("/*", index):
            end = text.find("*/", index + 2)
            if end < 0:
                raise ValueError("Unclosed settings comment")
            index = end + 2
            continue
        start = index
        if char == '"':
            index += 1
            while index < len(text):
                if text[index] == "\\":
                    index += 2
                elif text[index] == '"':
                    index += 1
                    break
                else:
                    index += 1
            else:
                raise ValueError("Unclosed settings string")
        elif char in "{}[]:,":
            index += 1
        else:
            while index < len(text) and not text[index].isspace() and text[index] not in "{}[]:,/":
                index += 1
            if index == start:
                raise ValueError("Invalid settings token")
        tokens.append((text[start:index], start, index))
    return tokens


def read_object(path):
    text = path.read_text() if path.exists() else "{}\n"
    tokens = jsonc_tokens(text)
    cleaned = " ".join(token[0] for i, token in enumerate(tokens)
                       if not (token[0] == "," and i + 1 < len(tokens) and tokens[i + 1][0] in ("}", "]")))
    value = json.loads(cleaned)
    if not isinstance(value, dict):
        raise ValueError("Application settings must be an object")
    return text, tokens, value


def update_object(path, updates):
    """Replace selected top-level values; retain all other bytes and reject bad JSON."""
    text, tokens, value = read_object(path)
    spans = {}
    depth = 0
    for index, (token, start, end) in enumerate(tokens):
        if token in ("{", "["):
            depth += 1
        elif token in ("}", "]"):
            depth -= 1
        elif depth == 1 and token.startswith('"') and index + 1 < len(tokens) and tokens[index + 1][0] == ":":
            key = json.loads(token)
            begin = index + 2
            finish = begin
            nested = 0
            while finish < len(tokens):
                current = tokens[finish][0]
                if nested == 0 and current in (",", "}"):
                    break
                if current in ("{", "["):
                    nested += 1
                elif current in ("}", "]"):
                    nested -= 1
                finish += 1
            if key in spans:
                raise ValueError("Duplicate settings property")
            spans[key] = (tokens[begin][1], tokens[finish - 1][2])
    replacements = []
    missing = []
    for key, item in updates.items():
        if key in value and value[key] == item:
            continue
        encoded = json.dumps(item, ensure_ascii=False, indent=2)
        if key in spans:
            start, end = spans[key]
            replacements.append((start, end, encoded))
        else:
            missing.append(json.dumps(key) + ": " + encoded)
    if missing:
        close = tokens[-1][1]
        comma = bool(value) and tokens[-2][0] != ","
        replacements.append((close, close, ("," if comma else "") + "\n  " + ",\n  ".join(missing) + "\n"))
    for start, end, encoded in sorted(replacements, reverse=True):
        text = text[:start] + encoded + text[end:]
    # Validate the complete edited document before any replacement.
    edited_tokens = jsonc_tokens(text)
    json.loads(" ".join(t[0] for i, t in enumerate(edited_tokens)
                        if not (t[0] == "," and i + 1 < len(edited_tokens) and edited_tokens[i + 1][0] in ("}", "]"))))
    return atomic_write(path, text)


def install_vscode(theme_path, palette_path):
    home = Path.home()
    config = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    data = Path(os.environ.get("XDG_DATA_HOME", home / ".local/share"))
    theme = json.loads(theme_path.read_text())
    atomic_write(data / "anto-desktop/vscode-palette.json", palette_path.read_text())
    installed = 0
    for root in (".vscode", ".vscode-insiders", ".vscode-oss", ".vscodium"):
        for package in (home / root / "extensions").glob("*/package.json"):
            manifest = json.loads(package.read_text())
            if manifest.get("name") != "anto426-vscode-theme":
                continue
            for entry in manifest.get("contributes", {}).get("themes", []):
                relative = entry.get("path", "")
                target = (package.parent / relative).resolve()
                if not target.is_relative_to(package.parent.resolve()):
                    raise ValueError("Theme path escapes installed extension")
                atomic_write(target, theme_path.read_text())
            installed += 1
    if not installed:
        extension = home / ".vscode/extensions/anto426.anto426-vscode-theme-dynamic"
        manifest = dict(name="anto426-vscode-theme", displayName="Anto426 Dynamic", version="0.2.0",
                        publisher="Anto426", engines={"vscode": "^1.100.0"}, categories=["Themes"],
                        contributes={"themes": [{"label": theme["name"], "uiTheme": "vs-dark", "path": "./themes/Anto426-Rofi-Dynamic.json"}]})
        atomic_write(extension / "package.json", json.dumps(manifest, indent=2) + "\n")
        atomic_write(extension / "themes/Anto426-Rofi-Dynamic.json", theme_path.read_text())
    for application in ("Code", "Code - Insiders", "Code - OSS", "VSCodium"):
        user = config / application / "User"
        if application != "Code" and not user.parent.exists():
            continue
        for settings in [user / "settings.json", *user.glob("profiles/*/settings.json")]:
            _, _, current = read_object(settings)
            name = f'[{theme["name"]}]'
            updates = {"workbench.colorTheme": theme["name"], "workbench.preferredDarkColorTheme": theme["name"]}
            for key, entry in (("workbench.colorCustomizations", theme["colors"]),
                               ("editor.tokenColorCustomizations", {"textMateRules": theme["tokenColors"]}),
                               ("editor.semanticTokenColorCustomizations", {"enabled": True, "rules": theme["semanticTokenColors"]})):
                existing = current.get(key, {})
                if not isinstance(existing, dict):
                    raise ValueError("Invalid theme customization settings")
                updates[key] = {**existing, name: entry}
            update_object(settings, updates)
    print("VS Code palette installed")


def render_obsidian(template, palette):
    values = dict(palette)
    for key, value in palette.items():
        if not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
            raise ValueError(f"Invalid palette role: {key}")
        values[key + "_rgb"] = ", ".join(str(int(value[i:i + 2], 16)) for i in (1, 3, 5))
    rgb = [int(palette["accent"][i:i + 2], 16) / 255 for i in (1, 3, 5)]
    hue, light, saturation = colorsys.rgb_to_hls(*rgb)
    values.update(accent_h=f"{hue * 360:.2f}", accent_s=f"{saturation * 100:.2f}", accent_l=f"{light * 100:.2f}")
    return re.sub(r"\{\{(\w+)\}\}", lambda match: values[match[1]], template)


def install_obsidian(resources, palette_path):
    home = Path.home()
    config = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    registry = config / "obsidian/obsidian.json"
    vaults = set()
    if registry.is_file():
        vaults.update(Path(entry["path"]) for entry in json.loads(registry.read_text()).get("vaults", {}).values() if entry.get("path"))
    vaults.update(Path(path) for path in os.environ.get("ANTO426_OBSIDIAN_VAULTS", "").split(os.pathsep) if path)
    manifest_text = (resources / "manifest.json").read_text()
    manifest = json.loads(manifest_text)
    if manifest["name"] != "Anto426 Monet":
        raise ValueError("Unexpected Obsidian theme identity")
    css = render_obsidian((resources / "template.css").read_text(), json.loads(palette_path.read_text()))
    installed = 0
    for vault in sorted(vaults):
        if not vault.is_dir():
            continue
        settings = vault / ".obsidian"
        appearance = settings / "appearance.json"
        _, _, current = read_object(appearance)
        snippets = current.get("enabledCssSnippets", [])
        if not isinstance(snippets, list):
            raise ValueError("Invalid Obsidian snippet settings")
        theme = settings / "themes" / manifest["name"]
        atomic_write(theme / "manifest.json", manifest_text)
        atomic_write(theme / "theme.css", (resources / "theme.css").read_text())
        atomic_write(settings / "snippets/anto426-palette.css", css)
        update_object(appearance, {"cssTheme": manifest["name"], "theme": "obsidian",
                                  "enabledCssSnippets": list(dict.fromkeys([*snippets, "anto426-palette"]))})
        installed += 1
    print(f"Obsidian palette installed in {installed} vault(s)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("application", choices=["vscode", "obsidian", "gtk", "qt"])
    parser.add_argument("artifact", type=Path)
    parser.add_argument("palette", type=Path)
    args = parser.parse_args()
    if args.application == "vscode":
        install_vscode(args.artifact, args.palette)
    elif args.application == "obsidian":
        install_obsidian(args.artifact, args.palette)
    elif args.application == "gtk":
        install_gtk(args.artifact)
    else:
        install_qt(args.artifact)


if __name__ == "__main__":
    main()
