[General]
Background=Backgrounds/anto426-current.png
MainColor=#edf1f8
AccentColor=#b4c8ff
BackgroundColor=#141820
SurfaceColor=#242b37
BorderColor=#414b5e
MutedColor=#a1adbf
ErrorColor=#f3a1aa
OverrideLoginButtonTextColor=#111722
AllowEmptyPassword=false
Locale=it_IT
Font=Noto Sans
