source = ~/.config/hypr/conf/theme.generated.conf

general {
    hide_cursor = false
    ignore_empty_input = true
    immediate_render = true
    text_trim = true
    fail_timeout = 1600
}

animations {
    enabled = true
}

background {
    monitor =
    path = $anto426_wallpaper
    color = $anto426_background
    blur_passes = 2
    blur_size = 5
    noise = 0.006
    contrast = 0.94
    brightness = 0.70
    vibrancy = 0.08
    vibrancy_darkness = 0.0
}

shape {
    monitor =
    size = 680, 390
    color = $anto426_background_soft
    rounding = 24
    border_size = 2
    border_color = $anto426_border_panel
    position = 0, 0
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 12
    shadow_color = $anto426_shadow
    zindex = 0
}

shape {
    monitor =
    size = 600, 1
    color = $anto426_border_soft
    rounding = 1
    position = 0, 38
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = $anto426_foreground_strong
    font_size = 76
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 98
    halign = center
    valign = center
    shadow_passes = 0
    zindex = 2
}

label {
    monitor =
    text = cmd[update:43200000] echo "$(date +'%A, %d %B')"
    color = $anto426_muted
    font_size = 16
    font_family = JetBrainsMono Nerd Font SemiBold
    position = 0, 52
    halign = center
    valign = center
    shadow_passes = 0
    zindex = 2
}

label {
    monitor =
    text = 󰌾 Sessione bloccata
    color = $anto426_accent_strong
    font_size = 14
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -4
    halign = center
    valign = center
    shadow_passes = 0
    zindex = 2
}

input-field {
    monitor =
    size = 520, 54
    outline_thickness = 1
    dots_size = 0.22
    dots_spacing = 0.28
    dots_center = true
    dots_rounding = -1

    outer_color = $anto426_border
    inner_color = $anto426_surface_panel
    font_color = $anto426_foreground
    font_family = JetBrainsMono Nerd Font

    fade_on_empty = false
    placeholder_text = Password
    hide_input = false
    rounding = 14

    check_color = $anto426_accent_soft
    fail_color = rgba(f38ba8cc)
    capslock_color = rgba(f38ba8cc)
    numlock_color = $anto426_accent_soft
    fail_text = $FAIL ($ATTEMPTS)
    fail_transition = 180

    position = 0, -78
    halign = center
    valign = center
    shadow_passes = 0
    zindex = 2
}

label {
    monitor =
    text = Layout: $LAYOUT
    color = $anto426_muted
    font_size = 11
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, -138
    halign = center
    valign = center
    shadow_passes = 0
    zindex = 2
}
