#  █████╗ ██████╗ ██████╗ ███████╗ █████╗ ██████╗  █████╗ ███╗   ██╗ ██████╗███████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔════╝██╔════╝     
# ███████║██████╔╝██████╔╝█████╗  ███████║██████╔╝███████║██╔██╗ ██║██║     █████╗     
# ██╔══██║██╔═══╝ ██╔═══╝ ██╔══╝  ██╔══██║██╔══██╗██╔══██║██║╚██╗██║██║     ██╔══╝   
# ██║  ██║██║     ██║     ███████╗██║  ██║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗   
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝  
#-----------------------------------------------------------------------------------

source = ~/.config/hypr/conf/theme.generated.conf


general {
    gaps_in = 2
    gaps_out = 5

    border_size = 0

    col.active_border = $anto426_active_border
    col.inactive_border = $anto426_inactive_border

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 2
        render_power = 2
        color = $anto426_shadow
    }

    blur {
        enabled = yes
        size = 8
        passes = 4
        new_optimizations = on
        ignore_opacity = off
        popups = false
        popups_ignorealpha = 0.7
        input_methods = false
    }
}

# Blur waybar
layerrule = blur on, match:namespace waybar
# Blur wlogout
layerrule = blur on, match:namespace logout_dialog
layerrule = dim_around false, match:namespace logout_dialog
# Blur swaync
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.99, match:namespace swaync-notification-window
layerrule = dim_around false, match:namespace swaync-control-center
layerrule = dim_around false, match:namespace swaync-notification-window

# Blur rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi
layerrule = dim_around false, match:namespace rofi

# Blur OSD component like rofi.
layerrule = blur on, match:namespace anto426-osd
layerrule = ignore_alpha 0.5, match:namespace anto426-osd
layerrule = dim_around false, match:namespace anto426-osd
