#!/usr/bin/env python3
"""Exercise application installation, JSONC preservation and vault boundaries."""
from pathlib import Path
import importlib.util
import json
import os
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("app_themes", ROOT / "support/compat/app_themes.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)


class Themes(unittest.TestCase):
    def test_ini_retains_fonts_comments_and_last_line(self):
        with tempfile.TemporaryDirectory() as folder:
            file = Path(folder) / "qt.conf"
            file.write_text("; personal preference\n[Appearance]\nstyle=Fusion\n[Fonts]\ngeneral=My Font,17")
            updates = {"Appearance": {"style": "kvantum", "custom_palette": "true"}, "Fonts": {"fixed": "Mono,12"}}
            module.update_ini(file, updates)
            self.assertIn("; personal preference", file.read_text())
            self.assertIn("general=My Font,17\nfixed=Mono,12", file.read_text())
            before = file.stat().st_mtime_ns
            module.update_ini(file, updates)
            self.assertEqual(file.stat().st_mtime_ns, before)
            file.write_text("[Settings]\nkey=one\nkey=two\n")
            with self.assertRaises(module.configparser.Error):
                module.update_ini(file, {"Settings": {"key": "new"}})
            self.assertIn("key=two", file.read_text())

    def test_gtk_imports_preserve_custom_css_fonts_and_use_modern_dark_preference(self):
        with tempfile.TemporaryDirectory() as folder:
            home = Path(folder)
            config = home / 'config'
            artifact = home / 'theme'
            for version in ('3.0', '4.0'):
                destination = config / ('gtk-' + version)
                destination.mkdir(parents=True)
                (destination / 'settings.ini').write_text("[Settings]\n; my font\ngtk-font-name=Custom 17\ngtk-application-prefer-dark-theme=true\n")
                css = '/* Generated by wallpaper_effects.sh */\nscale > trough > slider:active {\n color: red;\n}\n/* My override */\nbutton.custom {padding:19px;}\n'
                (destination / 'gtk.css').write_text(css)
                source = artifact / ('gtk-' + version)
                source.mkdir(parents=True)
                (source / 'palette.css').write_text('window {background:rgba(1,2,3,.46);}\n')
            with patch.dict(os.environ, HOME=folder, XDG_CONFIG_HOME=str(config), XDG_DATA_HOME=str(home / 'data')):
                module.install_gtk(artifact)
                for version in ('3.0', '4.0'):
                    directory = config / ('gtk-' + version)
                    self.assertIn('/* My override */\nbutton.custom {padding:19px;}', (directory / 'gtk.css').read_text())
                    self.assertNotIn('color: red', (directory / 'gtk.css').read_text())
                    self.assertIn('gtk-font-name=Custom 17', (directory / 'settings.ini').read_text())
                    self.assertEqual('gtk-application-prefer-dark-theme=true' in (directory / 'settings.ini').read_text(), version == '3.0')
                before = {file: file.stat().st_mtime_ns for file in config.rglob('*') if file.is_file()}
                module.install_gtk(artifact)
                self.assertEqual(before, {file: file.stat().st_mtime_ns for file in before})

    def test_qt_preserves_other_stylesheets_fonts_and_environment(self):
        with tempfile.TemporaryDirectory() as folder:
            home = Path(folder)
            config = home / 'config'
            artifact = home / 'theme'
            artifact.mkdir()
            for name in ('qt5.conf', 'qt6.conf', 'qt5.qss', 'qt6.qss', 'anto426.svg', 'anto426.kvconfig', 'qtquickcontrols2.conf'):
                (artifact / name).write_text('managed content @ANTO_QT_ASSETS@/check.svg\n')
            (artifact / 'assets').mkdir()
            (artifact / 'assets/check.svg').write_text('<svg/>')
            (artifact / 'qml/Anto426').mkdir(parents=True)
            (artifact / 'qml/Anto426/Button.qml').write_text('native template')
            for version in (5, 6):
                directory = config / f'qt{version}ct'
                directory.mkdir(parents=True)
                (directory / f'qt{version}ct.conf').write_text('[Fonts]\ngeneral=Custom,17\n[Interface]\nstylesheets=/my/custom.qss\n')
            environment = config / 'environment.d/99-anto426-qt.conf'
            environment.parent.mkdir(parents=True)
            environment.write_text('# Keep this\nOTHER_VAR=keep\nQT_STYLE_OVERRIDE=kvantum\n')
            with patch.dict(os.environ, HOME=folder, XDG_CONFIG_HOME=str(config), XDG_DATA_HOME=str(home / 'data')):
                module.install_qt(artifact)
                self.assertIn('OTHER_VAR=keep', environment.read_text())
                self.assertIn('QT_STYLE_OVERRIDE=\n', environment.read_text())
                self.assertIn('QT_QUICK_CONTROLS_STYLE_PATH=', environment.read_text())
                self.assertTrue((home / 'data/anto-desktop/qml/Anto426/Button.qml').is_file())
                for version in (5, 6):
                    text = (config / f'qt{version}ct/qt{version}ct.conf').read_text()
                    self.assertIn('general=Custom,17', text)
                    self.assertIn('stylesheets=/my/custom.qss, ', text)
                    self.assertTrue((config / f'qt{version}ct/anto426-assets/check.svg').is_file())
                    self.assertNotIn('@ANTO_QT_ASSETS@', (config / f'qt{version}ct/anto426.qss').read_text())
                before = {file: file.stat().st_mtime_ns for file in config.rglob('*') if file.is_file()}
                module.install_qt(artifact)
                self.assertEqual(before, {file: file.stat().st_mtime_ns for file in before})

    def test_jsonc_preserves_unrelated_comments_strings_and_values(self):
        with tempfile.TemporaryDirectory() as folder:
            file = Path(folder) / "settings.json"
            file.write_text('{\n // my editor\n "url": "https://host/x,}",\n "nested": {"array": [1,2,],},\n "managed": 1, // keep this comment\n}\n')
            module.update_object(file, {"managed": {"colors": ["#ffaa00"]}, "new": True})
            text = file.read_text()
            self.assertIn('"url": "https://host/x,}"', text)
            self.assertIn('"nested": {"array": [1,2,],}', text)
            self.assertIn('// keep this comment', text)
            self.assertEqual(module.read_object(file)[2]["managed"], {"colors": ["#ffaa00"]})
            before = file.stat().st_mtime_ns
            module.update_object(file, {"managed": {"colors": ["#ffaa00"]}, "new": True})
            self.assertEqual(file.stat().st_mtime_ns, before)

    def test_bad_settings_are_not_replaced(self):
        with tempfile.TemporaryDirectory() as folder:
            file = Path(folder) / "settings.json"
            for malformed in ('{"key":', '{"key":1,"key":2}', '[]', '{/* unclosed'):
                file.write_text(malformed)
                with self.assertRaises((ValueError, IndexError)):
                    module.update_object(file, {"key": 3})
                self.assertEqual(file.read_text(), malformed)

    def test_registered_vaults_keep_notes_plugins_and_other_snippets(self):
        original = dict(os.environ)
        try:
            with tempfile.TemporaryDirectory() as folder:
                home = Path(folder)
                os.environ.update(HOME=folder, XDG_CONFIG_HOME=str(home / "config"))
                os.environ.pop("ANTO426_OBSIDIAN_VAULTS", None)
                vault = home / "vault"
                settings = vault / ".obsidian"
                settings.mkdir(parents=True)
                note = vault / "personal.md"
                note.write_text("User text must stay byte-identical.\n")
                appearance = settings / "appearance.json"
                appearance.write_text('{"cssTheme":"Minimal","enabledCssSnippets":["custom"],"baseFontSize":18}')
                plugins = settings / "community-plugins.json"
                plugins.write_text('["user-plugin"]')
                registry = home / "config/obsidian/obsidian.json"
                registry.parent.mkdir(parents=True)
                registry.write_text(json.dumps({"vaults": {"a": {"path": str(vault)}, "missing": {"path": str(home / "absent")}}}))
                resources = home / "resources"
                resources.mkdir()
                (resources / "manifest.json").write_text('{"name":"Anto426 Monet"}')
                (resources / "theme.css").write_text('body { color: var(--text-normal); }')
                (resources / "template.css").write_text('body.theme-dark { --text-accent: {{accent}}; --accent-h: {{accent_h}}; }')
                palette = home / "palette.json"
                palette.write_text('{"accent":"#66aacc"}')
                module.install_obsidian(resources, palette)
                current = module.read_object(appearance)[2]
                self.assertEqual(current["enabledCssSnippets"], ["custom", "anto426-palette"])
                self.assertEqual(current["baseFontSize"], 18)
                self.assertEqual(note.read_text(), "User text must stay byte-identical.\n")
                self.assertEqual(plugins.read_text(), '["user-plugin"]')
                self.assertFalse((home / "absent").exists())
                times = {file: file.stat().st_mtime_ns for file in settings.rglob("*") if file.is_file()}
                module.install_obsidian(resources, palette)
                self.assertEqual(times, {file: file.stat().st_mtime_ns for file in times})
        finally:
            os.environ.clear()
            os.environ.update(original)

    def test_vscode_preserves_profile_and_theme_customizations(self):
        original = dict(os.environ)
        try:
            with tempfile.TemporaryDirectory() as folder:
                home = Path(folder)
                os.environ.update(HOME=folder, XDG_CONFIG_HOME=str(home / "config"), XDG_DATA_HOME=str(home / "data"))
                profile = home / "config/Code/User/profiles/one/settings.json"
                profile.parent.mkdir(parents=True)
                profile.write_text('{// profile comment\n"editor.fontSize":17,"workbench.colorCustomizations":{"[Other]":{"foreground":"#112233"}},}')
                theme = home / "theme.json"
                theme.write_text(json.dumps(dict(name="Anto426 Rofi Dynamic", colors={"modernUI.shellBackground": "#11223344"}, tokenColors=[], semanticTokenColors={"class": "#112233"})))
                palette = home / "palette.json"
                palette.write_text('{"accent":"#112233"}')
                module.install_vscode(theme, palette)
                current = module.read_object(profile)[2]
                self.assertEqual(current["editor.fontSize"], 17)
                self.assertIn("// profile comment", profile.read_text())
                self.assertIn("[Other]", current["workbench.colorCustomizations"])
                self.assertEqual(current["workbench.colorCustomizations"]["[Anto426 Rofi Dynamic]"]["modernUI.shellBackground"], "#11223344")
        finally:
            os.environ.clear()
            os.environ.update(original)


if __name__ == "__main__":
    unittest.main()
